
const teams=[
['Baltimore Ravens','BAL','#241773','#9e7c0c'],['Buffalo Bills','BUF','#00338d','#c60c30'],['Detroit Lions','DET','#0076b6','#b0b7bc'],['Philadelphia Eagles','PHI','#004c54','#a5acaf'],['Kansas City Chiefs','KC','#e31837','#ffb81c'],['Green Bay Packers','GB','#203731','#ffb612'],['New England Patriots','NE','#002244','#c60c30'],['Seattle Seahawks','SEA','#002244','#69be28'],['Dallas Cowboys','DAL','#041e42','#869397'],['San Francisco 49ers','SF','#aa0000','#b3995d'],['Cleveland Browns','CLE','#311d00','#ff3c00'],['Houston Texans','HOU','#03202f','#a71930']
];
const games=[['NE','SEA'],['SF','LAR'],['ATL','PIT'],['CLE','JAX'],['BUF','HOU'],['KC','LV'],['DAL','PHI']];
const aliases={LAR:['Los Angeles Rams','LAR','#003594','#ffa300'],ATL:['Atlanta Falcons','ATL','#a71930','#000'],PIT:['Pittsburgh Steelers','PIT','#101820','#ffb612'],JAX:['Jacksonville Jaguars','JAX','#101820','#00a5b5'],LV:['Las Vegas Raiders','LV','#000','#a5acaf']};
Object.values(aliases).forEach(t=>teams.push(t));
let activeGame=0;
const defs=[['eff','Efficiency',92],['median','Median YPP',76],['exp','Explosives',80],['neg','Negative Plays',74],['qb','QB',90],['trenches','Trenches',68],['coverage','Coverage Match',80],['pace','Pace',48],['rz','Red Zone',72],['turn','Turnovers',54],['inj','Injuries',72],['field','Field Position',40]];
const weights=Object.fromEntries(defs.map(x=>[x[0],x[2]]));
const injuries={
NE:[['TreVeyon Henderson','RB','Questionable','q'],['Khalil Jacobs','LB','IR','out']],SEA:[['Zach Charbonnet','RB','OUT / PUP','out'],['Jadarian Price','RB','↑ Lead role','up']],
GB:[['Josh Jacobs','RB','Unavailable','out'],['MarShawn Lloyd','RB','↑ RB1','up']],DET:[['Isiah Pacheco','RB','IR','out'],['Jahmyr Gibbs','RB','↑ Workload','up']],
SF:[['George Kittle','TE','↑ Practicing','up']],CLE:[['Dillon Gabriel','QB','IR','out'],['Shedeur Sanders','QB','↑ QB2','up']],HOU:[['Tank Dell','WR','IR','out']],DAL:[['Sam Howell','QB','↑ QB2','up']]
};
function tdata(abbr){return teams.find(t=>t[1]===abbr)||[abbr,abbr,'#415466','#9aa4ad']}
function logoUrl(abbr){const map={JAX:'jax',LAR:'lar',LV:'lv'};const code=(map[abbr]||abbr).toLowerCase();return `https://a.espncdn.com/i/teamlogos/nfl/500/${code}.png`}
function logoImg(abbr,name,cls=''){return `<img class="${cls}" src="${logoUrl(abbr)}" alt="${name} logo" onerror="this.style.display='none';this.parentElement.dataset.fallback='${abbr}'">`}
function hash(s){let h=2166136261;for(const c of s){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function raw(team,key){return 45+(hash('NFL'+team+key)%5100)/100}
function matchup(a,b){let score=0,total=0,details=[];defs.forEach(([k,label])=>{const av=raw(a,k),bv=raw(b,k),w=weights[k]/100,c=(av-bv)/100*w;score+=c;total+=w;details.push({k,label,av,bv,c,w:weights[k]})});score/=Math.sqrt(total||1);const p=1/(1+Math.exp(-score*8.2));return{a,b,p,details:details.sort((x,y)=>Math.abs(y.c)-Math.abs(x.c))}}
function project(team,opp,winP){const eff=(raw(team,'eff')-50)/50,med=(raw(team,'median')-50)/50,pace=(raw(team,'pace')-50)/50,rz=(raw(team,'rz')-50)/50,exp=(raw(team,'exp')-50)/50,qb=(raw(team,'qb')-50)/50,tr=(raw(team,'trenches')-50)/50,cov=(raw(team,'coverage')-50)/50,neg=(raw(team,'neg')-50)/50,to=(raw(team,'turn')-50)/50,field=(raw(team,'field')-50)/50,inj=(raw(team,'inj')-50)/50;const plays=58+12*pace*(weights.pace/100)+2.4*(winP-.5);const passRate=Math.min(.74,Math.max(.40,.55+.07*qb*(weights.qb/100)+.04*cov*(weights.coverage/100)-.02*tr));const att=plays*passRate;const compPct=Math.min(.78,Math.max(.46,.605+.075*qb*(weights.qb/100)+.032*cov*(weights.coverage/100)+.015*med*(weights.median/100)));const comp=att*compPct;const passYPA=5.9+2.15*eff*(weights.eff/100)+1.15*exp*(weights.exp/100)+.7*cov*(weights.coverage/100)+.55*qb*(weights.qb/100)+.3*inj*(weights.inj/100);const passYds=att*passYPA;const rushAtt=plays-att;const rushYPC=3.45+1.3*tr*(weights.trenches/100)+.65*eff*(weights.eff/100)+.35*exp*(weights.exp/100);const rushYds=rushAtt*rushYPC;const totalYds=passYds+rushYds;const firstDowns=Math.max(9,totalYds/18+rz*1.5+neg*1.2);const turnovers=Math.max(.2,1.5-.64*to*(weights.turn/100)-.28*qb*(weights.qb/100));const points=Math.max(8,11.5+totalYds/34.5+rz*5.5*(weights.rz/100)+exp*2.2*(weights.exp/100)+field*1.7*(weights.field/100)+inj*1.1*(weights.inj/100)-turnovers*1.15);const passTD=Math.max(.2,points*.061+qb*.32),rushTD=Math.max(.15,points*.034+tr*.2),ints=Math.max(.08,turnovers*.68);return{plays,att,comp,compPct,passYds,rushAtt,rushYds,totalYds,firstDowns,turnovers,points,passTD,rushTD,ints,passRate}}
function players(team,t){const ypr=t.passYds/Math.max(1,t.comp),qbRush=Math.max(6,t.rushYds*.12),rbRec=t.comp*.10,wr1=t.comp*.28,wr2=t.comp*.22,slot=t.comp*.20,te=t.comp*.16;const ppr=(rec,recY,recTD,rushY=0,rushTD=0,passY=0,passTD=0,intc=0)=>rec+recY/10+recTD*6+rushY/10+rushTD*6+passY/25+passTD*4-intc*2;return[
{pos:'QB',name:'QB1',vol:t.att,yds:t.passYds,fp:ppr(0,0,0,qbRush,0,t.passYds,t.passTD,t.ints),role:'Starter'},
{pos:'RB',name:'RB1',vol:t.rushAtt*.64,yds:t.rushYds*.62+rbRec*ypr*.72,fp:ppr(rbRec,rbRec*ypr*.72,t.passTD*.08,t.rushYds*.62,t.rushTD*.68),role:'Lead'},
{pos:'WR',name:'WR1',vol:t.att*.27,yds:wr1*ypr*1.18,fp:ppr(wr1,wr1*ypr*1.18,t.passTD*.34),role:'Primary'},
{pos:'WR',name:'WR2',vol:t.att*.22,yds:wr2*ypr*1.03,fp:ppr(wr2,wr2*ypr*1.03,t.passTD*.24),role:'Starter'},
{pos:'WR',name:'SLOT',vol:t.att*.21,yds:slot*ypr*.82,fp:ppr(slot,slot*ypr*.82,t.passTD*.16),role:'Slot'},
{pos:'TE',name:'TE1',vol:t.att*.16,yds:te*ypr*.79,fp:ppr(te,te*ypr*.79,t.passTD*.18),role:'Starter'}]}

function randn(){let u=0,v=0;while(u===0)u=Math.random();while(v===0)v=Math.random();return Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*v)}
function qtile(a,q){if(!a.length)return 0;const x=(a.length-1)*q,i=Math.floor(x),f=x-i;return a[i+1]!==undefined?a[i]*(1-f)+a[i+1]*f:a[i]}
function currentContext(){const [a,b]=games[activeGame],A=tdata(a),B=tdata(b),m=matchup(a,b),ta=project(a,b,m.p),tb=project(b,a,1-m.p);let list=[...players(a,ta).map(x=>({...x,team:A[1],teamCode:a})),...players(b,tb).map(x=>({...x,team:B[1],teamCode:b}))];return{a,b,A,B,m,ta,tb,list}}
function playerBase(p,stat){return stat==='yds'?p.yds:stat==='fp'?p.fp:p.vol}
function playerJointValue(p,stat,c,sa,sb){const base=playerBase(p,stat),own=p.teamCode===c.a?sa:sb,opp=p.teamCode===c.a?sb:sa,ownMean=p.teamCode===c.a?c.ta.points:c.tb.points,oppMean=p.teamCode===c.a?c.tb.points:c.ta.points,totalMean=c.ta.points+c.tb.points;const ownDelta=(own-ownMean)/Math.max(13,ownMean),totalDelta=((sa+sb)-totalMean)/Math.max(24,totalMean),margin=((own-opp)-(ownMean-oppMean))/18;let script=.30*ownDelta+.10*totalDelta,cv=stat==='yds'?.27:stat==='fp'?.28:.16;if(p.pos==='QB')script=.42*ownDelta+.22*totalDelta-.08*margin;if(p.pos==='RB')script=.34*ownDelta+.08*totalDelta+.24*margin;if(p.pos==='WR'||p.pos==='TE')script=.40*ownDelta+.23*totalDelta-.10*margin;if(stat==='fp')script*=1.12;if(stat==='vol')script*=.70;let v=Math.max(0,base*(1+script+randn()*cv));if(stat==='vol')v=Math.max(0,Math.round(v*2)/2);return v}
function simPopulate(){const c=currentContext();for(const id of ['simTeam','condTeam','targetTeam']){const el=document.getElementById(id);if(!el)continue;const old=el.value;el.innerHTML=`<option value="${c.a}">${c.A[0]}</option><option value="${c.b}">${c.B[0]}</option>`;if([c.a,c.b].includes(old))el.value=old}for(const id of ['simPlayer','targetPlayer']){const el=document.getElementById(id);if(!el)continue;const old=el.value;el.innerHTML=c.list.map((x,i)=>`<option value="${i}">${x.team} ${x.name} · ${x.pos}</option>`).join('');if(old!==''&&c.list[+old])el.value=old}simModeUI(false);conditionalUI(false)}
function simModeUI(resetLine=true){const mode=document.getElementById('simMode')?.value;if(!mode)return;document.getElementById('simPlayerWrap').classList.toggle('hidden',mode!=='player');document.getElementById('simStatWrap').classList.toggle('hidden',mode!=='player');document.getElementById('simTeamWrap').classList.toggle('hidden',mode==='total'||mode==='player');const c=currentContext(),line=document.getElementById('simLine'),lab=document.getElementById('simLineLabel');if(mode==='total'){lab.textContent='OVER / UNDER LINE';if(resetLine)line.value=(c.ta.points+c.tb.points).toFixed(1)}else if(mode==='team'){lab.textContent='TEAM POINTS LINE';let t=document.getElementById('simTeam').value||c.a;if(resetLine)line.value=(t===c.a?c.ta.points:c.tb.points).toFixed(1)}else if(mode==='margin'){lab.textContent='SELECTED TEAM SPREAD / MARGIN LINE';if(resetLine)line.value='-3.5'}else{lab.textContent='PLAYER PROP LINE';if(resetLine)simPlayerLine()}if(resetLine&&document.getElementById('valueLine'))document.getElementById('valueLine').value=line.value}
function simPlayerLine(){const c=currentContext(),i=+(document.getElementById('simPlayer')?.value||0),stat=document.getElementById('simStat')?.value||'yds',p=c.list[i]||c.list[0],line=document.getElementById('simLine');if(!p||!line)return;line.value=playerBase(p,stat).toFixed(stat==='fp'?1:stat==='vol'?1:0);if(document.getElementById('valueLine'))document.getElementById('valueLine').value=line.value}
function scoreDraw(meanA,meanB){const pace=randn()*2.7,za=randn(),zb=randn();const a=Math.max(0,Math.round(meanA+pace+za*8.2)),b=Math.max(0,Math.round(meanB+pace+zb*8.2));return[a,b]}
function metricValue(mode,team,p,stat,c,sa,sb){if(mode==='total')return sa+sb;if(mode==='team')return team===c.a?sa:sb;if(mode==='margin')return team===c.a?sa-sb:sb-sa;return playerJointValue(p,stat,c,sa,sb)}
function metricBase(mode,team,p,stat,c){if(mode==='total')return c.ta.points+c.tb.points;if(mode==='team')return team===c.a?c.ta.points:c.tb.points;if(mode==='margin')return team===c.a?c.ta.points-c.tb.points:c.tb.points-c.ta.points;return playerBase(p,stat)}
function metricLabel(mode,team,p,stat,c){if(mode==='total')return'Game total';if(mode==='team')return(team===c.a?c.A[1]:c.B[1])+' points';if(mode==='margin')return(team===c.a?c.A[1]:c.B[1])+' margin';return`${p.team} ${p.name} ${stat==='yds'?'yards':stat==='fp'?'fantasy points':'opportunities'}`}
function generateMetricRuns(c,mode,n,team,p,stat){const vals=[],scores={};for(let i=0;i<n;i++){const [sa,sb]=scoreDraw(c.ta.points,c.tb.points);scores[`${sa}-${sb}`]=(scores[`${sa}-${sb}`]||0)+1;vals.push(metricValue(mode,team,p,stat,c,sa,sb))}return{vals,scores}}
let lastSimResult=null;
function runSimulation(){const c=currentContext(),mode=document.getElementById('simMode').value,n=Math.max(100,Math.min(100000,Math.round(+document.getElementById('simCount').value||10000))),line=+document.getElementById('simLine').value||0,team=document.getElementById('simTeam').value||c.a,stat=document.getElementById('simStat').value||'yds',pi=+(document.getElementById('simPlayer').value||0),p=c.list[pi]||c.list[0];document.getElementById('simCount').value=n;const out=generateMetricRuns(c,mode,n,team,p,stat),vals=out.vals.sort((a,b)=>a-b),scores=out.scores,base=metricBase(mode,team,p,stat,c),label=metricLabel(mode,team,p,stat,c);let over=0,under=0,push=0;for(const v of vals){if(v>line)over++;else if(v<line)under++;else push++}const mean=vals.reduce((a,b)=>a+b,0)/vals.length,med=qtile(vals,.5),p10=qtile(vals,.1),p90=qtile(vals,.9),op=over/n*100,up=under/n*100,pp=push/n*100;lastSimResult={c,mode,n,line,team,stat,pi,p,vals,over,under,push};document.getElementById('simRunLabel').textContent=n.toLocaleString()+' RUNS';document.getElementById('simMean').textContent=mean.toFixed(1);document.getElementById('simMeanDesc').textContent=label+' · model '+base.toFixed(1);document.getElementById('simOver').textContent=op.toFixed(1)+'%';document.getElementById('simUnder').textContent=up.toFixed(1)+'%';document.getElementById('simMedian').textContent=med.toFixed(1);document.getElementById('simRange').textContent=`${p10.toFixed(1)}–${p90.toFixed(1)} 10th–90th`;document.getElementById('simOverBar').style.width=op+'%';document.getElementById('simUnderBar').style.width=(100-op)+'%';document.getElementById('simOverBar').textContent=op>13?`ABOVE ${op.toFixed(0)}%`:'';document.getElementById('simUnderBar').textContent=(100-op)>13?`BELOW ${(100-op).toFixed(0)}%`:'';let edge=mean-line,detail=[['YOUR LINE',line.toFixed(1)],['MODEL EDGE',(edge>=0?'+':'')+edge.toFixed(1)],['PUSH',pp.toFixed(1)+'%']];if(mode!=='player'){let top=Object.entries(scores).sort((a,b)=>b[1]-a[1]).slice(0,3);if(top.length)detail.push(['MOST COMMON SCORE',top[0][0]+' · '+(top[0][1]/n*100).toFixed(1)+'%'])}document.getElementById('simDetails').innerHTML=detail.map(x=>`<div class="sim-score-row"><span>${x[0]}</span><span>${x[1]}</span></div>`).join('');renderHist(vals,line);document.getElementById('simNote').textContent=`${n.toLocaleString()} Monte Carlo outcomes for ${label}. Player outcomes are now simulated jointly with the game score so conditional game-script questions can be tested.`;document.getElementById('valueLine').value=line;runValueCheck()}
function renderHist(vals,line){const el=document.getElementById('simHist');if(!el||!vals.length)return;const bins=32,min=vals[0],max=vals[vals.length-1],span=Math.max(.001,max-min),cnt=Array(bins).fill(0);vals.forEach(v=>{let i=Math.min(bins-1,Math.floor((v-min)/span*bins));cnt[i]++});const mx=Math.max(...cnt);el.innerHTML=cnt.map(c=>`<div class="hist-bar" style="height:${Math.max(2,c/mx*150)}px"></div>`).join('')+`<div class="hist-line" style="left:${Math.max(0,Math.min(100,(line-min)/span*100))}%"></div><div class="hist-label" style="left:0%">${min.toFixed(0)}</div><div class="hist-label" style="left:50%">${((min+max)/2).toFixed(0)}</div><div class="hist-label" style="left:100%">${max.toFixed(0)}</div>`}
function conditionalUI(reset=true){const c=currentContext(),ct=document.getElementById('condType')?.value||'win',tm=document.getElementById('targetMode')?.value||'player';if(!document.getElementById('condTeamWrap'))return;document.getElementById('condTeamWrap').classList.toggle('hidden',ct.startsWith('total_'));document.getElementById('condLineWrap').classList.toggle('hidden',ct==='win'||ct==='lose');document.getElementById('targetTeamWrap').classList.toggle('hidden',tm==='total'||tm==='player');document.getElementById('targetPlayerWrap').classList.toggle('hidden',tm!=='player');document.getElementById('targetStatWrap').classList.toggle('hidden',tm!=='player');if(reset){const cl=document.getElementById('condLine');if(ct.startsWith('total_'))cl.value=(c.ta.points+c.tb.points).toFixed(1);else if(ct.startsWith('team_')){const t=document.getElementById('condTeam').value||c.a;cl.value=(t===c.a?c.ta.points:c.tb.points).toFixed(1)}else if(ct.startsWith('margin_'))cl.value='-3.5';targetDefaultLine()}}
function targetDefaultLine(){const c=currentContext(),mode=document.getElementById('targetMode')?.value||'player',team=document.getElementById('targetTeam')?.value||c.a,pi=+(document.getElementById('targetPlayer')?.value||0),p=c.list[pi]||c.list[0],stat=document.getElementById('targetStat')?.value||'yds',line=document.getElementById('targetLine');if(!line)return;line.value=metricBase(mode,team,p,stat,c).toFixed(mode==='player'&&stat==='yds'?0:1)}
function conditionPass(type,team,line,c,sa,sb){const own=team===c.a?sa:sb,opp=team===c.a?sb:sa;if(type==='win')return own>opp;if(type==='lose')return own<opp;if(type==='total_over')return sa+sb>line;if(type==='total_under')return sa+sb<line;if(type==='team_over')return own>line;if(type==='team_under')return own<line;if(type==='margin_over')return own-opp>line;if(type==='margin_under')return own-opp<line;return false}
function runConditional(){const c=currentContext(),n=Math.max(100,Math.min(100000,Math.round(+document.getElementById('simCount').value||10000))),ct=document.getElementById('condType').value,cteam=document.getElementById('condTeam').value||c.a,cline=+document.getElementById('condLine').value||0,tm=document.getElementById('targetMode').value,tteam=document.getElementById('targetTeam').value||c.a,pi=+(document.getElementById('targetPlayer').value||0),p=c.list[pi]||c.list[0],stat=document.getElementById('targetStat').value||'yds',side=document.getElementById('targetSide').value,line=+document.getElementById('targetLine').value||0;let cond=0,target=0,both=0;for(let i=0;i<n;i++){const[sa,sb]=scoreDraw(c.ta.points,c.tb.points),cp=conditionPass(ct,cteam,cline,c,sa,sb),v=metricValue(tm,tteam,p,stat,c,sa,sb),hit=side==='over'?v>line:v<line;if(cp)cond++;if(hit)target++;if(cp&&hit)both++}const cpct=cond/n*100,overall=target/n*100,given=cond?both/cond*100:0,lift=given-overall;document.getElementById('condOccurs').textContent=cpct.toFixed(1)+'%';document.getElementById('condSample').textContent=cond.toLocaleString()+' qualifying runs';document.getElementById('targetOverall').textContent=overall.toFixed(1)+'%';document.getElementById('targetConditional').textContent=(cond?given.toFixed(1):'—')+(cond?'%':'');document.getElementById('targetLift').textContent=(cond?(lift>=0?'+':'')+lift.toFixed(1)+' pp':'—');const condName=document.getElementById('condType').selectedOptions[0].textContent,targetName=metricLabel(tm,tteam,p,stat,c),teamName=cteam===c.a?c.A[0]:c.B[0];document.getElementById('conditionalNote').textContent=`IF ${ct.startsWith('total_')?'game':teamName} ${condName.toLowerCase()}${ct==='win'||ct==='lose'?'':' '+cline.toFixed(1)}, THEN ${targetName} ${side} ${line.toFixed(1)} hit ${given.toFixed(1)}% of qualifying simulations versus ${overall.toFixed(1)}% overall. Conditional lift: ${(lift>=0?'+':'')+lift.toFixed(1)} percentage points.`}
function americanToDecimal(o){return o>0?1+o/100:1+100/Math.abs(o)}
function americanImplied(o){return o>0?100/(o+100):Math.abs(o)/(Math.abs(o)+100)}
function probToAmerican(p){if(p<=0)return'+∞';if(p>=1)return'-∞';const o=p<.5?100*(1-p)/p:-100*p/(1-p);return(o>0?'+':'')+Math.round(o)}
function runValueCheck(){const c=currentContext(),mode=document.getElementById('simMode').value,n=Math.max(100,Math.min(100000,Math.round(+document.getElementById('simCount').value||10000))),line=+document.getElementById('valueLine').value||0,side=document.getElementById('valueSide').value,odds=+document.getElementById('valueOdds').value||0,team=document.getElementById('simTeam').value||c.a,stat=document.getElementById('simStat').value||'yds',pi=+(document.getElementById('simPlayer').value||0),p=c.list[pi]||c.list[0],out=generateMetricRuns(c,mode,n,team,p,stat);let win=0,loss=0,push=0;for(const v of out.vals){if(v===line)push++;else if(side==='over'?(v>line):(v<line))win++;else loss++}const simP=(win+loss)?win/(win+loss):0,imp=americanImplied(odds),dec=americanToDecimal(odds),profit100=100*(dec-1),ev=(win/n)*profit100-(loss/n)*100,edge=(simP-imp)*100,fair=probToAmerican(simP),good=ev>0;document.getElementById('valueSimProb').textContent=(simP*100).toFixed(1)+'%';document.getElementById('valueImplied').textContent=(imp*100).toFixed(1)+'%';document.getElementById('valueFairOdds').textContent=fair;document.getElementById('valueEdge').textContent=(edge>=0?'+':'')+edge.toFixed(1)+' pp';document.getElementById('valueEV').textContent=(ev>=0?'+':'')+'$'+Math.abs(ev).toFixed(2);document.getElementById('valuePayout').textContent='$'+profit100.toFixed(2);const box=document.getElementById('valueVerdict');box.classList.remove('good','bad');box.classList.add(good?'good':'bad');document.getElementById('valueHeadline').textContent=good?'POSITIVE MODEL VALUE':'NO MODEL VALUE';document.getElementById('valueSummary').textContent=`${side.toUpperCase()} ${line.toFixed(1)} at ${odds>0?'+':''}${odds}: simulator ${(simP*100).toFixed(1)}% vs market break-even ${(imp*100).toFixed(1)}%. Model fair price ${fair}.`;document.getElementById('valueNote').textContent=`At a $100 stake, this price pays $${profit100.toFixed(2)} profit if it wins. Across ${n.toLocaleString()} simulations, estimated EV is ${(ev>=0?'+':'')}$${Math.abs(ev).toFixed(2)} per $100 staked. Pushes (${(push/n*100).toFixed(1)}%) are treated as stake returned.`}
function renderStrip(){const s=document.getElementById('scoreStrip');s.querySelectorAll('.game-chip').forEach(x=>x.remove());games.forEach((g,i)=>{const a=tdata(g[0]),b=tdata(g[1]);const el=document.createElement('div');el.className='game-chip'+(i===activeGame?' active':'');el.innerHTML=`<div class="when">WEEK 1 • 1:00 PM</div><div class="chip-team"><span class="chip-side">${logoImg(a[1],a[0],'chip-logo')}<span>${a[1]}</span></span><span class="chip-score">0-0</span></div><div class="chip-team"><span class="chip-side">${logoImg(b[1],b[0],'chip-logo')}<span>${b[1]}</span></span><span class="chip-score">0-0</span></div>`;el.onclick=()=>{activeGame=i;render();refreshChatRoom()};s.appendChild(el)})}
function injuryRows(a,b,full=false){let rows=[...(injuries[a]||[]),...(injuries[b]||[])];if(!rows.length)rows=[['No major role changes','—','Current','up']];return rows.map(r=>`<div class="inj-row"><div><div class="inj-name">${r[0]}</div><div class="inj-pos">${r[1]}</div></div><div class="status ${r[3]}">${r[2]}</div></div>`).join('')}
function tableRows(list){return list.map(x=>`<tr><td><b>${x.name}</b></td><td>${x.pos}</td><td>${x.team}</td><td class="num"><b>${x.fp.toFixed(1)}</b></td><td class="num optional-col">${x.vol.toFixed(1)}</td><td class="num optional-col">${x.yds.toFixed(0)}</td><td><span class="tag ${x.role==='Lead'?'up':''}">${x.role}</span></td></tr>`).join('')}
function render(){renderStrip();const [a,b]=games[activeGame],A=tdata(a),B=tdata(b);const m=matchup(a,b),ta=project(a,b,m.p),tb=project(b,a,1-m.p);document.documentElement.style.setProperty('--teamA',A[2]);document.documentElement.style.setProperty('--teamB',B[2]);document.getElementById('teamNameA').textContent=A[0];document.getElementById('teamNameB').textContent=B[0];document.getElementById('teamMetaA').textContent='0-0 • Home';document.getElementById('teamMetaB').textContent='0-0 • Away';['markA','markB'].forEach((id,idx)=>{const t=idx?B:A,el=document.getElementById(id);el.innerHTML=logoImg(t[1],t[0]);el.style.background='#fff';el.style.border=`1px solid ${t[2]}22`;});
const pa=m.p*100,pb=100-pa;document.getElementById('pA').textContent=pa.toFixed(1)+'%';document.getElementById('pB').textContent=pb.toFixed(1)+'%';document.getElementById('pALabel').textContent=A[1];document.getElementById('pBLabel').textContent=B[1];document.getElementById('donut').style.setProperty('--pB',pb+'%');document.getElementById('donut').style.background=`conic-gradient(${B[2]} 0 ${pb}%, #e8ecef ${pb}% 100%)`;document.getElementById('predA').textContent=ta.points.toFixed(1);document.getElementById('predB').textContent=tb.points.toFixed(1);document.getElementById('predALabel').textContent=A[1];document.getElementById('predBLabel').textContent=B[1];const edge=Math.abs(m.p-.5);document.getElementById('confidenceText').textContent='MODEL CONFIDENCE: '+(edge>.20?'HIGH':edge>.09?'MEDIUM':'LOW');document.getElementById('heroA').textContent=Math.round(ta.points);document.getElementById('heroB').textContent=Math.round(tb.points);document.getElementById('leanText').textContent=(m.p>=.5?A[0]:B[0])+' by '+Math.abs(ta.points-tb.points).toFixed(1);
const why=m.details.slice(0,5);document.getElementById('whyRows').innerHTML=why.map(d=>`<div class="why-row"><div class="lbl">${d.label}</div><div class="meter"><i style="width:${Math.min(100,Math.abs(d.c)*650)}%"></i></div><div class="val">${d.c>=0?A[1]:B[1]}</div></div>`).join('');document.getElementById('trendRows').innerHTML=m.details.map(d=>`<div class="why-row"><div class="lbl">${d.label}</div><div class="meter"><i style="width:${Math.min(100,Math.abs(d.c)*650)}%"></i></div><div class="val">${d.c>=0?A[1]:B[1]}</div></div>`).join('');
const metrics=[['TOTAL',ta.points+tb.points,'pts'],['TOTAL YARDS',ta.totalYds+tb.totalYds,'yds'],['PLAYS',ta.plays+tb.plays,'snaps'],['PASS RATE',(ta.passRate+tb.passRate)/2*100,'%']];document.getElementById('marketGrid').innerHTML=metrics.map(x=>`<div class="metric"><div class="k">${x[0]}</div><div class="v">${x[1].toFixed(x[2]==='%'?1:0)}${x[2]==='%'?'%':''}</div><div class="d">Projected ${x[2]}</div></div>`).join('');
let list=[...players(a,ta).map(x=>({...x,team:A[1]})),...players(b,tb).map(x=>({...x,team:B[1]}))].sort((x,y)=>y.fp-x.fp);document.getElementById('leaders').innerHTML=list.slice(0,3).map(x=>`<div class="leader"><div class="avatar">${x.pos}</div><div><div class="name">${x.team} ${x.name}</div><div class="role">${x.role} • ${x.vol.toFixed(1)} projected opportunities</div></div><div class="fp">${x.fp.toFixed(1)} <small>FPTS</small></div></div>`).join('');document.getElementById('playerRows').innerHTML=tableRows(list.slice(0,8));document.getElementById('allPlayerRows').innerHTML=tableRows(list);
const inj=injuryRows(a,b);document.getElementById('injuryList').innerHTML=inj;document.getElementById('injuryListFull').innerHTML=inj;document.getElementById('roleImpact').innerHTML=`<div class="metric"><div class="k">MODEL HANDLING</div><div class="v">Redistribute, don't delete</div><div class="d">Unavailable player volume is reassigned to the most likely replacement role based on the current depth chart.</div></div><div class="metric" style="margin-top:10px"><div class="k">CURRENT MATCHUP</div><div class="v">${A[1]} vs ${B[1]}</div><div class="d">Starter-watch signals feed the projection layer when confirmed.</div></div>`;
const cards=(t,label)=>`<div style="display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin-bottom:14px"><div class="metric"><div class="k">${label} POINTS</div><div class="v">${t.points.toFixed(1)}</div></div><div class="metric"><div class="k">TOTAL YDS</div><div class="v">${t.totalYds.toFixed(0)}</div></div><div class="metric"><div class="k">PASS YDS</div><div class="v">${t.passYds.toFixed(0)}</div></div><div class="metric"><div class="k">RUSH YDS</div><div class="v">${t.rushYds.toFixed(0)}</div></div></div>`;document.getElementById('projectionBody').innerHTML=cards(ta,A[1])+cards(tb,B[1]);document.getElementById('heatTeamA').textContent=A[0];document.getElementById('heatTeamB').textContent=B[0];document.getElementById('newsList').innerHTML=[['TODAY','Starter watch synced to matchup','Confirmed roster and role changes are designed to flow into the active projection rather than sit as separate news.'],['GAME WEEK','Heat-map layer ready','Target density, run lanes and defensive vulnerability can occupy the familiar game-center card space.'],['MODEL','Projection logic preserved','This redesign changes the interface first; the existing projection model remains underneath.']].map(x=>`<div class="news-item"><div class="news-time">${x[0]}</div><div class="news-head">${x[1]}</div><div class="news-note">${x[2]}</div></div>`).join('');simPopulate()}
document.getElementById('simMode').addEventListener('change',()=>simModeUI(true));document.getElementById('simTeam').addEventListener('change',()=>simModeUI(true));document.getElementById('simPlayer').addEventListener('change',simPlayerLine);document.getElementById('simStat').addEventListener('change',simPlayerLine);document.getElementById('runSimBtn').addEventListener('click',runSimulation);document.getElementById('condType').addEventListener('change',()=>conditionalUI(true));document.getElementById('condTeam').addEventListener('change',()=>conditionalUI(true));document.getElementById('targetMode').addEventListener('change',()=>conditionalUI(true));document.getElementById('targetTeam').addEventListener('change',targetDefaultLine);document.getElementById('targetPlayer').addEventListener('change',targetDefaultLine);document.getElementById('targetStat').addEventListener('change',targetDefaultLine);document.getElementById('runConditionalBtn').addEventListener('click',runConditional);document.getElementById('runValueBtn').addEventListener('click',runValueCheck);

// ---------- Community chat + social sharing ----------
const CHAT_CONFIG={supabaseUrl:'',supabaseAnonKey:'',table:'edgework_chat'}; // add public anon credentials at deployment to enable multi-user Realtime
let chatBackend='local';
let chatClient=null,chatChannel=null;
function activePair(){return games[activeGame]||['A','B']}
function roomKey(){const [a,b]=activePair();return `NFL-W1-${a}-${b}`}
function roomLabel(){const [a,b]=activePair();return `${tdata(a)[0]} vs ${tdata(b)[0]}`}
function escHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function currentProjectionShareText(){const [a,b]=activePair(),A=tdata(a),B=tdata(b),m=matchup(a,b),ta=project(a,b,m.p),tb=project(b,a,1-m.p);const fav=m.p>=.5?A[0]:B[0],pct=(Math.max(m.p,1-m.p)*100).toFixed(1);return `EDGEWORK: ${A[0]} ${Math.round(ta.pts)} – ${Math.round(tb.pts)} ${B[0]} | ${fav} ${pct}% win probability | Projected total ${(ta.pts+tb.pts).toFixed(1)}.`}
function currentShareUrl(){return location.protocol==='file:'?'https://edgework.app/':location.href.split('#')[0]}
function prepareShare(){const t=document.getElementById('shareText');if(t)t.value=currentProjectionShareText()}
async function copyPreparedShare(){prepareShare();const text=document.getElementById('shareText')?.value||currentProjectionShareText();try{await navigator.clipboard.writeText(text);setShareStatus('Projection text copied.')}catch(e){const t=document.getElementById('shareText');t?.focus();t?.select();setShareStatus('Select and copy the prepared text.')}return text}
function setShareStatus(msg){const el=document.getElementById('shareStatus');if(el)el.textContent=msg}
function openShare(){prepareShare();document.getElementById('shareModal')?.classList.add('open');document.getElementById('shareModal')?.setAttribute('aria-hidden','false')}
function closeShare(){document.getElementById('shareModal')?.classList.remove('open');document.getElementById('shareModal')?.setAttribute('aria-hidden','true')}
function postToX(){prepareShare();const text=document.getElementById('shareText')?.value||currentProjectionShareText();const u=`https://twitter.com/intent/tweet?text=${encodeURIComponent(text)}&url=${encodeURIComponent(currentShareUrl())}`;window.open(u,'_blank','noopener,noreferrer')}
async function postToFacebook(){await copyPreparedShare();const u=`https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(currentShareUrl())}`;window.open(u,'_blank','noopener,noreferrer');setShareStatus('Projection text copied. Paste it into Facebook if the composer does not carry it automatically.')}
async function nativeShare(){prepareShare();const text=document.getElementById('shareText')?.value||currentProjectionShareText();if(navigator.share){try{await navigator.share({title:'EDGEWORK Matchup',text,url:currentShareUrl()});return}catch(e){if(e?.name==='AbortError')return}}await copyPreparedShare()}
function localChatRead(){try{return JSON.parse(localStorage.getItem('edgework.chat.'+roomKey())||'[]')}catch(e){return[]}}
function localChatWrite(rows){localStorage.setItem('edgework.chat.'+roomKey(),JSON.stringify(rows.slice(-150)))}
function currentChatName(){return (localStorage.getItem('edgework.chat.name')||'Guest').slice(0,28)}
function setChatName(v){v=(v||'Guest').trim().slice(0,28)||'Guest';localStorage.setItem('edgework.chat.name',v);return v}
function renderChat(rows=localChatRead()){const feed=document.getElementById('chatFeed');if(!feed)return;const me=currentChatName();if(!rows.length){feed.innerHTML='<div class="chat-empty">No messages in this matchup room yet.<br>Start the conversation.</div>';return}feed.innerHTML=rows.map(r=>`<div class="chat-msg ${r.name===me?'mine':''}"><div class="chat-msg-head"><span class="chat-user">${escHtml(r.name)}</span><span class="chat-time">${new Date(r.created_at||Date.now()).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}</span></div><div class="chat-text">${escHtml(r.message)}</div></div>`).join('');feed.scrollTop=feed.scrollHeight}
async function sendChat(){const input=document.getElementById('chatInput');if(!input)return;const message=input.value.trim();if(!message)return;const name=setChatName(document.getElementById('chatName')?.value||currentChatName());input.value='';const row={room:roomKey(),name,message,created_at:new Date().toISOString()};if(chatBackend==='supabase'&&chatClient){const {error}=await chatClient.from(CHAT_CONFIG.table).insert(row);if(error){console.warn(error);const rows=localChatRead();rows.push(row);localChatWrite(rows);renderChat(rows)}}else{const rows=localChatRead();rows.push(row);localChatWrite(rows);renderChat(rows)}}
async function loadCloudChat(){if(!chatClient)return;const {data,error}=await chatClient.from(CHAT_CONFIG.table).select('room,name,message,created_at').eq('room',roomKey()).order('created_at',{ascending:true}).limit(150);if(!error)renderChat(data||[])}
async function subscribeCloudChat(){if(!chatClient)return;if(chatChannel){await chatClient.removeChannel(chatChannel);chatChannel=null}await loadCloudChat();chatChannel=chatClient.channel('edgework-'+roomKey()).on('postgres_changes',{event:'INSERT',schema:'public',table:CHAT_CONFIG.table,filter:`room=eq.${roomKey()}`},()=>loadCloudChat()).subscribe()}
async function initCloudChat(){if(!CHAT_CONFIG.supabaseUrl||!CHAT_CONFIG.supabaseAnonKey)return;try{const mod=await import('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm');chatClient=mod.createClient(CHAT_CONFIG.supabaseUrl,CHAT_CONFIG.supabaseAnonKey);chatBackend='supabase';document.getElementById('chatMode').textContent='LIVE';await subscribeCloudChat()}catch(e){console.warn('EDGEWORK chat using local fallback',e)}}
function refreshChatRoom(){const rn=document.getElementById('chatRoomName'),hh=document.getElementById('chatHeader');if(rn)rn.textContent=roomLabel();if(hh)hh.textContent=roomLabel().toUpperCase()+' CHAT';const name=document.getElementById('chatName');if(name)name.value=currentChatName();if(chatBackend==='supabase')subscribeCloudChat();else renderChat()}
function bindCommunity(){document.getElementById('openShareBtn')?.addEventListener('click',openShare);document.getElementById('shareClose')?.addEventListener('click',closeShare);document.getElementById('shareModal')?.addEventListener('click',e=>{if(e.target.id==='shareModal')closeShare()});document.getElementById('shareXBtn')?.addEventListener('click',postToX);document.getElementById('shareFBBtn')?.addEventListener('click',postToFacebook);document.getElementById('shareCopyBtn')?.addEventListener('click',copyPreparedShare);document.getElementById('nativeShareBtn')?.addEventListener('click',nativeShare);document.getElementById('chatSendBtn')?.addEventListener('click',sendChat);document.getElementById('chatInput')?.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendChat()}});document.getElementById('chatName')?.addEventListener('change',e=>{setChatName(e.target.value);renderChat()});document.getElementById('chatShareX')?.addEventListener('click',postToX);document.getElementById('chatShareFB')?.addEventListener('click',postToFacebook);document.getElementById('chatCopy')?.addEventListener('click',copyPreparedShare);refreshChatRoom();initCloudChat()}
document.getElementById('tabs').addEventListener('click',e=>{const b=e.target.closest('.tab');if(!b)return;document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.section').forEach(x=>x.classList.remove('active'));document.getElementById(b.dataset.tab).classList.add('active')});
render();simPopulate();runSimulation();runConditional();

bindCommunity();
