/* AWM V3 live prediction engine.
   Source of truth: Advantage_Winner_Model_Week_4_2026.xlsx.
   Fixed architecture: 60% football matchup / 35% power / 5% current form.
   College Week 4 uses the workbook's exact 71-game outputs.
   Market lines are comparison-only and never alter the pregame AWM prediction.
*/
(function(){
const NFL_FIELDS=["offYpp","defYpp","median","defMedian","expl","explAllowed","neg","negForced","power","form","ppg","papg","yards","yardsAllowed","passYds","passYdsAllowed","rushYds","rushYdsAllowed","plays","defPlays","passAtt","comp","rushAtt","passRate","firstDowns","firstDownsAllowed","defPassAtt","defComp","defRushAtt"];
const NFL_TEAMS=[["Arizona Cardinals","ARI","#97233F","#000000"],["Atlanta Falcons","ATL","#A71930","#000000"],["Baltimore Ravens","BAL","#241773","#9E7C0C"],["Buffalo Bills","BUF","#00338D","#C60C30"],["Carolina Panthers","CAR","#0085CA","#101820"],["Chicago Bears","CHI","#0B162A","#C83803"],["Cincinnati Bengals","CIN","#FB4F14","#000000"],["Cleveland Browns","CLE","#311D00","#FF3C00"],["Dallas Cowboys","DAL","#041E42","#869397"],["Denver Broncos","DEN","#FB4F14","#002244"],["Detroit Lions","DET","#0076B6","#B0B7BC"],["Green Bay Packers","GB","#203731","#FFB612"],["Houston Texans","HOU","#03202F","#A71930"],["Indianapolis Colts","IND","#002C5F","#A2AAAD"],["Jacksonville Jaguars","JAX","#101820","#00A5B5"],["Kansas City Chiefs","KC","#E31837","#FFB81C"],["Las Vegas Raiders","LV","#000000","#A5ACAF"],["Los Angeles Chargers","LAC","#0080C6","#FFC20E"],["Los Angeles Rams","LAR","#003594","#FFA300"],["Miami Dolphins","MIA","#008E97","#FC4C02"],["Minnesota Vikings","MIN","#4F2683","#FFC62F"],["New England Patriots","NE","#002244","#C60C30"],["New Orleans Saints","NO","#D3BC8D","#101820"],["New York Giants","NYG","#0B2265","#A71930"],["New York Jets","NYJ","#125740","#000000"],["Philadelphia Eagles","PHI","#004C54","#A5ACAF"],["Pittsburgh Steelers","PIT","#FFB612","#101820"],["San Francisco 49ers","SF","#AA0000","#B3995D"],["Seattle Seahawks","SEA","#002244","#69BE28"],["Tampa Bay Buccaneers","TB","#D50A0A","#FF7900"],["Tennessee Titans","TEN","#0C2340","#4B92DB"],["Washington Commanders","WAS","#5A1414","#FFB612"]];
const NFL_WEEK3=[["ATL","GB"],["LAC","BUF"],["CAR","CLE"],["NYJ","DET"],["HOU","IND"],["NE","JAX"],["KC","MIA"],["TEN","NYG"],["CIN","PIT"],["SEA","WAS"],["ARI","SF"],["MIN","TB"],["LV","NO"],["BAL","DAL"],["LAR","DEN"],["PHI","CHI"]];
const NFL_META={"ATL@GB":"THU • 8:15 PM","LAC@BUF":"SUN • 1:00 PM","CAR@CLE":"SUN • 1:00 PM","NYJ@DET":"SUN • 1:00 PM","HOU@IND":"SUN • 1:00 PM","NE@JAX":"SUN • 1:00 PM","KC@MIA":"SUN • 1:00 PM","TEN@NYG":"SUN • 1:00 PM","CIN@PIT":"SUN • 1:00 PM","SEA@WAS":"SUN • 1:00 PM","ARI@SF":"SUN • 4:05 PM","MIN@TB":"SUN • 4:05 PM","LV@NO":"SUN • 4:25 PM","BAL@DAL":"SUN • 4:25 PM","LAR@DEN":"SUN • 8:20 PM","PHI@CHI":"MON • 8:15 PM"};
const DATA_FILES=["awm_college_profiles.js","awm_college_exact.js","awm_college_aliases.js","awm_nfl_profiles.js"];
function load(src){return new Promise((ok,bad)=>{const s=document.createElement("script");s.src=src;s.async=false;s.onload=ok;s.onerror=bad;document.head.appendChild(s)})}
const norm=s=>String(s||"").toLowerCase().replace(/&/g,"and").replace(/[^a-z0-9]+/g," ").replace(/\b(university|college|the)\b/g,"").replace(/\s+/g," ").trim();
function cname(s){const n=norm(s),A=window.AWM_COLLEGE_ALIASES||{},P=window.AWM_COLLEGE_PROFILES||{},a=A[n];if(a&&P[a])return a;for(const k in P)if(norm(k)===n)return k;let best="";for(const k in P){const q=norm(k);if((n.startsWith(q+" ")||q.startsWith(n+" "))&&q.length>best.length)best=k}return best||null}
function cp(name){const k=cname(name),a=k&&(window.AWM_COLLEGE_PROFILES||{})[k];return a?{name:k,d:a[0],g:a[1],oy:a[2],dy:a[3],m:a[4],dm:a[5],e:a[6],ea:a[7],n:a[8],nf:a[9],p:a[10],f:a[11]}:null}
function cr(name){const p=cp(name);return p?{name:p.name,division:p.d,off:p.oy,def:p.dy,ppg:null,papg:null,g26:p.g,power:p.p,form:p.f,median:p.m,defMedian:p.dm,explosive:p.e,explosiveAllowed:p.ea,negative:p.n,negativeForced:p.nf}:null}
function cfb(A,H){const eff=(H.oy-A.dy)-(A.oy-H.dy),med=(H.m-A.dm)-(A.m-H.dm),exp=((H.e+A.ea)/2)-((A.e+H.ea)/2),neg=((A.n+H.nf)/2)-((H.n+A.nf)/2);return 5*eff+1.5*med+70*exp+35*neg}
function cGeneric(away,home,neutral){const U={d:"FCS",g:0,oy:4.65,dy:6.35,m:2.7,dm:4.1,e:.045,ea:.105,n:.36,nf:.24,p:-20,f:0},A=cp(away)||U,H=cp(home)||U;const fb=cfb(A,H),power=(H.p||0)-(A.p||0),form=Math.max(-28,Math.min(28,H.f||0))-Math.max(-28,Math.min(28,A.f||0));let margin=.60*fb+.35*power+.05*form+(neutral?0:2.2);if(fb*power>0&&Math.abs(margin)>8)margin*=1+Math.min(.25,(Math.abs(fb)+Math.abs(power))/100);const ay=27+4*(A.oy-5.55)+3*(H.dy-5.55),hy=27+4*(H.oy-5.55)+3*(A.dy-5.55),total=Math.max(20,ay+hy),hs=Math.max(0,(total+margin)/2),as=Math.max(0,(total-margin)/2),hp=1/(1+Math.exp(-margin/7.8)),fcs=A.d==="FCS"||H.d==="FCS";return {away_score:+as.toFixed(1),home_score:+hs.toFixed(1),home_win_prob:+hp.toFixed(4),away_win_prob:+(1-hp).toFixed(4),source:"AWM V3",confidence:fcs?"LOW • FBS-FCS":hp>=.8||hp<=.2?"HIGH":hp>=.64||hp<=.36?"MEDIUM":"LOW",away_rating:cr(away),home_rating:cr(home),internal_margin:+margin.toFixed(2),model_margin:+margin.toFixed(2),market_margin:null,market_total:null,components:{football:+fb.toFixed(2),power:+power.toFixed(2),form:+form.toFixed(2)}}}
function cproject(away,home,neutral,market){const E=window.AWM_COLLEGE_EXACT_W4||{},ak=cname(away),hk=cname(home),x=E[(ak||away)+"@@"+(hk||home)];if(x)return {away_score:x[0],home_score:x[1],home_win_prob:x[2],away_win_prob:1-x[2],source:"AWM V3 WEEK 4",confidence:x[3],away_rating:cr(away),home_rating:cr(home),internal_margin:x[1]-x[0],model_margin:x[1]-x[0],market_margin:market?.home_margin??null,market_total:market?.over_under??null,expected_total:x[4],away_expected_plays:x[5],home_expected_plays:x[6],away_expected_explosives:x[7],home_expected_explosives:x[8],away_median_yards:x[9],home_median_yards:x[10],away_negative_rate:x[11],home_negative_rate:x[12],impact_edge_home:x[13],fbs_fcs:x[14]||null};const r=cGeneric(away,home,neutral);r.market_margin=market?.home_margin??null;r.market_total=market?.over_under??null;return r}
window.GRIDLOCK_COLLEGE_MODEL={mean:27,rating:cr,project:cproject,version:"AWM V3 2026 Week 4 • 60 matchup / 35 power / 5 current form • market independent"};
function np(code){const a=(window.AWM_NFL_PROFILES||{})[code];if(!a)return null;const o={};NFL_FIELDS.forEach((k,i)=>o[k]=a[i]);return o}
function nedge(a,h){const A=np(a),H=np(h);if(!A||!H)return {margin:0,football:0,power:0,form:0};const eff=(H.offYpp-A.defYpp)-(A.offYpp-H.defYpp),med=(H.median-A.defMedian)-(A.median-H.defMedian),exp=((H.expl+A.explAllowed)/2)-((A.expl+H.explAllowed)/2),neg=((A.neg+H.negForced)/2)-((H.neg+A.negForced)/2),football=5*eff+1.5*med+70*exp+35*neg,power=H.power-A.power,form=Math.max(-28,Math.min(28,H.form))-Math.max(-28,Math.min(28,A.form));let margin=.60*football+.35*power+.05*form+1.5;if(football*power>0&&Math.abs(margin)>7)margin*=1+Math.min(.22,(Math.abs(football)+Math.abs(power))/90);return {margin,football,power,form}}
function nraw(t,k){const x=np(t);if(!x)return 50;const m={eff:50+(x.offYpp-5.23)*12,median:50+(x.median-3.5)*8,exp:50+(x.expl-.07)*220,neg:50+(.33-x.neg)*140,qb:50+(x.passYds-220)/7,trenches:50+(x.rushYds-115)/5,coverage:50+(220-x.passYdsAllowed)/7,pace:50+(x.plays-64)*2,rz:50+(x.ppg-22.76)*2,turn:50+(x.negForced-.33)*100,inj:50,field:50+x.power*1.3};return Math.max(5,Math.min(95,m[k]??50))}
function nmatch(a,h){const e=nedge(a,h),hw=1/(1+Math.exp(-e.margin/7.8)),aw=1-hw;return {a,b:h,p:aw,edge:-e.margin,details:[{k:"eff",label:"Football Matchup",c:-.60*e.football/25,av:nraw(a,"eff"),bv:nraw(h,"eff"),w:60},{k:"field",label:"Power",c:-.35*e.power/25,av:np(a)?.power||0,bv:np(h)?.power||0,w:35},{k:"pace",label:"Current Form",c:-.05*e.form/25,av:np(a)?.form||0,bv:np(h)?.form||0,w:5}].sort((x,y)=>Math.abs(y.c)-Math.abs(x.c)),awm:{...e,awayWin:aw,homeWin:hw}}}
function nproject(team,opp,winP){const T=np(team),O=np(opp);if(!T||!O)return {plays:64,att:34,comp:21,compPct:.62,passYds:220,rushAtt:27,rushYds:115,totalYds:335,firstDowns:20,turnovers:1.3,points:22,pts:22,passTD:1.3,rushTD:.8,ints:.8,passRate:.55};const plays=.5*T.plays+.5*O.defPlays,att=.5*T.passAtt+.5*O.defPassAtt,comp=.5*T.comp+.5*O.defComp,passYds=.5*T.passYds+.5*O.passYdsAllowed,rushAtt=.5*T.rushAtt+.5*O.defRushAtt,rushYds=.5*T.rushYds+.5*O.rushYdsAllowed,totalYds=passYds+rushYds,firstDowns=.5*T.firstDowns+.5*O.firstDownsAllowed,teamMargin=7.8*Math.log(Math.max(.001,winP)/Math.max(.001,1-winP)),baseTeam=.5*T.ppg+.5*O.papg,baseOpp=.5*O.ppg+.5*T.papg,total=baseTeam+baseOpp,points=(total+teamMargin)/2,compPct=comp/Math.max(1,att),passRate=att/Math.max(1,plays),turnovers=Math.max(.35,1.35-(T.negForced-.33)*1.5);return {plays,att,comp,compPct,passYds,rushAtt,rushYds,totalYds,firstDowns,turnovers,points,pts:points,passTD:Math.max(.15,points*.057),rushTD:Math.max(.10,points*.031),ints:Math.max(.08,turnovers*.58),passRate}}
// Public presentation adapter; the existing NFL calculations remain unchanged.
window.GRIDLOCK_NFL_MODEL={matchup:nmatch,project:nproject,profile:np,teams:NFL_TEAMS};
function activate(){try{raw=nraw;matchup=nmatch;project=nproject;NFL_TEAMS.forEach(t=>{if(typeof teams!=="undefined"&&!teams.some(x=>x[1]===t[1]))teams.push(t)});if(typeof games!=="undefined")games.splice(0,games.length,...NFL_WEEK3.map(x=>x.slice()));if(typeof renderStrip==="function")renderStrip=function(){const s=document.getElementById("scoreStrip");if(!s)return;s.querySelectorAll(".game-chip").forEach(x=>x.remove());games.forEach((g,i)=>{const a=tdata(g[0]),b=tdata(g[1]),el=document.createElement("div");el.className="game-chip"+(i===activeGame?" active":"");const when="WEEK 3 • "+(NFL_META[g[0]+"@"+g[1]]||"TBD");el.innerHTML=`<div class="when">${when}</div><div class="chip-team"><span class="chip-side">${logoImg(a[1],a[0],"chip-logo")}<span>${a[1]}</span></span><span class="chip-score">0-0</span></div><div class="chip-team"><span class="chip-side">${logoImg(b[1],b[0],"chip-logo")}<span>${b[1]}</span></span><span class="chip-score">0-0</span></div>`;el.onclick=()=>{activeGame=i;render();refreshChatRoom()};s.appendChild(el)})};if(typeof render==="function"){const legacy=render;render=function(){legacy();const A=document.getElementById("teamMetaA"),B=document.getElementById("teamMetaB");if(A)A.textContent="2026 • Away";if(B)B.textContent="2026 • Home"};activeGame=0;render();if(typeof simPopulate==="function")simPopulate()}window.GRIDLOCK_NFL_AWM_V3={edge:nedge,version:"AWM V3 NFL • 2025 PFF power baseline + 2026 Weeks 1-2 current form"}}catch(e){console.warn("AWM V3 NFL activation failed",e)}const w=document.getElementById("collegeWeek");if(w&&String(w.value)!=="4"){w.value="4";w.dispatchEvent(new Event("change"))}}
Promise.all(DATA_FILES.map(load)).then(()=>{activate();setTimeout(activate,350)}).catch(e=>console.error("AWM V3 data load failed",e));
})();