/* NFL presentation shares NCAA markup/styles while keeping league state and feeds isolated. */
(function () {
 'use strict';
 const root=document.createElement('section');root.id='nflCenter';root.className='section';
 const $=id=>root.querySelector('#'+id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const num=v=>v===null||v===undefined||v===''?null:Number.isFinite(Number(v))?Number(v):null;
 const fixed=v=>num(v)===null?'—':Number(v).toFixed(1), pct=v=>num(v)===null?'—':(v*100).toFixed(1)+'%';
 const row=(k,v)=>`<div class="cg-row"><span>${esc(k)}</span><b>${esc(v)}</b></div>`;
 const empty=s=>`<div class="cg-live-empty">${esc(s)}</div>`;
 const date=s=>new Date(s).toLocaleDateString('en-US',{weekday:'long',month:'short',day:'numeric'});
 const time=s=>new Date(s).toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit',timeZoneName:'short'});
 const api='https://site.api.espn.com/apis/site/v2/sports/football/nfl/';
 const season=2026;
 let week=Math.max(1,Math.min(18,Math.floor((Date.now()-Date.UTC(season,8,8))/(7*86400000))+1)),slate=[],selected=null,projection=null,loadToken=0,liveToken=0,tab='gamecast',lastSummary=null;
 // Clone only the NCAA structural template, before populating any NFL data. Namespace every ID.
 const detail=document.getElementById('collegeGamecast').cloneNode(true);
 detail.id='nflGamecast';detail.querySelectorAll('[id]').forEach(el=>el.id='nfl'+el.id.slice(2));
 detail.querySelectorAll('[data-cg]').forEach(el=>{el.dataset.nflTab=el.dataset.cg;delete el.dataset.cg});
 detail.querySelectorAll('[data-cg-panel]').forEach(el=>{el.dataset.nflPanel=el.dataset.cgPanel;delete el.dataset.cgPanel});
 detail.querySelector('#nflBack').textContent='← BACK TO NFL SLATE';
 detail.querySelector('#nflPostPlay').textContent='COPY PROJECTION';
 root.innerHTML=`<div class="college-shell" id="nflSlate"><div class="college-hero card">
 <div class="college-title-row"><div><div class="eyebrow">GRIDLOCK NFL</div><h2>NFL FOOTBALL SCHEDULE</h2><div class="college-sub">Weekly slate • live schedule sync • Advantage Winner Model projections</div><div style="margin-top:8px"><span class="college-model-badge">AUTO MODEL • NFL AWM V3</span></div></div><div class="college-source"><span id="nflSyncDot"></span><b id="nflSyncText">LOADING SCHEDULE</b><small>Schedule and live game data: ESPN</small></div></div>
 <div class="college-toolbar"><div class="week-nav"><button id="nflPrevWeek" aria-label="Previous NFL week">‹</button><select id="nflWeek" aria-label="NFL week">${Array.from({length:18},(_,i)=>`<option value="${i+1}">${season} • Week ${i+1}</option>`).join('')}</select><button id="nflNextWeek" aria-label="Next NFL week">›</button></div><select id="nflConf" aria-label="NFL conference"><option value="">ALL NFL</option><option>AFC</option><option>NFC</option></select><select id="nflState" aria-label="Game status"><option value="">ALL GAMES</option><option value="pre">PREGAME</option><option value="in">LIVE</option><option value="post">FINAL</option></select><input id="nflSearch" placeholder="Search team or matchup" aria-label="Search NFL games" autocomplete="off"><button class="college-action" id="nflRefresh">REFRESH</button></div>
 <div class="college-kpis"><div><b id="nflGameCount">—</b><span>GAMES</span></div><div><b id="nflProjectedCount">—</b><span>WITH PROJECTIONS</span></div><div><b id="nflTeamCount">—</b><span>NFL TEAMS ACTIVE</span></div><div><b id="nflUpdated">—</b><span>UPDATED</span></div></div></div>
 <div class="college-days" id="nflDays" aria-live="polite"></div><div class="college-empty" id="nflEmpty" hidden>No games match these filters.</div><div class="college-projection-note card"><b>ADVANTAGE WINNER MODEL</b><span>60% football matchup • 35% power • 5% current form. Market spread and total are comparison-only. Verified prior-game profiles and archived pregame snapshots; missing history remains unavailable.</span></div></div>`;
 root.append(detail);document.querySelector('main.main').append(root);
 // Analytics uses NFL profiles and box projections, never the college Power 4 lab.
 const analytics=root.querySelector('[data-nfl-panel="analytics"]');
 analytics.innerHTML='<div class="cg-grid"><div class="cg-card"><div class="cg-card-head">TEAM STRENGTH • NFL</div><div class="cg-card-body" id="nflAnalytics"></div></div><div class="cg-card"><div class="cg-card-head">PROJECTED TEAM BOX SCORE</div><div class="cg-card-body" id="nflBox"></div></div></div>';
 $('nflCalibration').previousElementSibling.textContent='MARKET COMPARISON';
 $('nflLiveProjection').closest('.cg-card').querySelector('.cg-card-head').firstChild.textContent='LIVE SCORE VS PREGAME ';
 $('nflMomentum').previousElementSibling.firstChild.textContent='LIVE TEAM STATS ';
 const afc=new Set('BAL BUF CIN CLE DEN HOU IND JAX KC LAC LV MIA NE NYJ PIT TEN'.split(' '));
 const code=s=>({WSH:'WAS',JAC:'JAX',LA:'LAR'}[s]||s);
 function parse(e){const c=e.competitions?.[0],cs=c?.competitors||[],a=cs.find(x=>x.homeAway==='away'),h=cs.find(x=>x.homeAway==='home');if(!a||!h)return null;
  const team=x=>{const t=x.team||{},abbr=code(t.abbreviation);return {id:t.id,abbr,name:t.displayName||abbr,logo:t.logo||t.logos?.[0]?.href||'',color:t.color,altColor:t.alternateColor,conf:afc.has(abbr)?'AFC':'NFC',record:x.records?.[0]?.summary||'',score:num(x.score)}};
  const away=team(a),home=team(h),o=c.odds?.[0]||{};let margin=null;const spread=num(o.spread);
  if(spread!==null){if(o.homeTeamOdds?.favorite)margin=Math.abs(spread);else if(o.awayTeamOdds?.favorite)margin=-Math.abs(spread);else {const m=(o.details||'').match(/([A-Z]+)\s*([+-]?\d+(?:\.\d+)?)/);if(m){const fav=code(m[1]),v=Number(m[2]);if(fav===home.abbr)margin=-v;else if(fav===away.abbr)margin=v;}if(spread===0)margin=0}}
  const st=c.status||e.status||{};return {id:String(e.id),date:e.date,away,home,venue:c.venue?.fullName||'',network:(c.broadcasts?.[0]?.names||[]).join(' / '),state:st.type?.state||'pre',status:st.type?.shortDetail||st.type?.description||'Scheduled',complete:!!st.type?.completed,market:{details:o.details||'',margin,total:num(o.overUnder),provider:o.provider?.name||''}};
 }
 function model(g){const f=AdvantageModel.project(AWM_DATA.NFL,{...g,league:'NFL'});if(!f.available)return null;return {forecast:f,away:{points:f.away_score,plays:f.expected.away.tempo,totalYds:f.expected.away.tempo*f.expected.away.ypp},home:{points:f.home_score,plays:f.expected.home.tempo,totalYds:f.expected.home.tempo*f.expected.home.ypp},ap:f.away_win_prob,hp:f.home_win_prob,edge:{...f.components,margin:f.margin},margin:f.margin,total:f.total};}
 function market(g){return g.market.details?`MARKET ${g.market.details}${g.market.total!==null?' • O/U '+g.market.total:''}`:g.market.total!==null?'MARKET O/U '+g.market.total:'MARKET LINE UNAVAILABLE'}
 function syncPick(g,p){if(!p||!window.GridlockPicks)return null;return window.GridlockPicks.syncGame({league:'NFL',gameId:g.id,week,date:g.date,away:g.away.name,home:g.home.name,awayAbbr:g.away.abbr,homeAbbr:g.home.abbr,modelHomeMargin:p.margin,marketHomeMargin:g.market.margin,marketDetails:g.market.details||'',complete:g.complete,awayFinal:g.away.score,homeFinal:g.home.score});}
 function gameCard(g){
  const p=model(g);
  let tierHTML='';
  if(p&&window.GridlockPicks){
    const modelMargin=Number(p.margin),marketMargin=Number(g.market.margin);
    if(Number.isFinite(modelMargin)&&Number.isFinite(marketMargin)){
      const signedEdge=modelMargin-marketMargin,edge=Math.abs(signedEdge),stars=window.GridlockPicks.tier('NFL',edge);
      if(stars){
        const side=signedEdge>=0?g.home:g.away;
        const spread=signedEdge>=0?-marketMargin:marketMargin;
        const line=(spread>0?'+':'')+spread.toFixed(1);
        tierHTML=`<div class="pick-slate-badge"><div class="pick-slate-main"><span class="pick-side">${esc(side.abbr||side.name)} ${line}</span><span class="pick-tier-pill"><span class="pick-stars">${window.GridlockPicks.stars(stars)}</span> ${stars}-STAR</span></div><span class="pick-slate-edge">${edge.toFixed(1)}-PT MODEL EDGE</span></div>`;
      }else{
        tierHTML=`<div class="pick-slate-badge"><span class="pick-slate-noplay">NO PLAY</span><span class="pick-slate-edge">${edge.toFixed(1)}-PT MODEL EDGE • BELOW 1★ THRESHOLD</span></div>`;
      }
    }else{
      tierHTML=`<div class="pick-slate-badge"><span class="pick-slate-noplay">NO STAR RATING</span><span class="pick-slate-edge">MARKET SPREAD UNAVAILABLE</span></div>`;
    }
  }
  const shareHTML=`<div class="main-card-share"><div class="main-card-share-hint">TAP A TEAM TO SHARE PICK</div><div class="main-card-share-actions"><span class="main-card-share-pick">SELECTED: —</span><button type="button" class="main-card-send msg" data-main-share="msg">MSG</button><button type="button" class="main-card-send x" data-main-share="x">X</button><button type="button" class="main-card-send fb" data-main-share="fb">FB</button></div></div>`;
  return `<div class="college-game" data-nfl-game="${esc(g.id)}" role="button" tabindex="0" aria-label="Open ${esc(g.away.name)} at ${esc(g.home.name)}"><div class="college-game-top"><span class="college-time">${esc(time(g.date))} • ${g.complete?'FINAL':g.state==='in'?'LIVE':'PREGAME'}</span><span class="college-network">${esc(g.network)}</span></div>${['away','home'].map(side=>{const t=g[side];return `<div class="college-team-row" data-share-side="${side}"><div class="nfl-card-name"><img src="${esc(t.logo)}" alt=""><div><div class="college-team-name">${esc(t.name)}</div><div class="college-team-conf">${t.conf} • ${esc(t.record||t.abbr)}</div></div></div><div class="college-proj ${p?'':'blank'}">PROJ ${p?fixed(p[side].points):'—'}</div><div class="college-score">${g.state==='pre'?'':t.score??'—'}</div></div>`}).join('')}<div class="college-game-bottom"><span class="college-status">${esc(market(g))}<br>${esc(g.status)}</span><span class="college-winprob">${p?`${g.home.abbr} ${pct(p.hp)} • ${g.away.abbr} ${pct(p.ap)}`:'MODEL UNAVAILABLE'}</span></div>${tierHTML}${shareHTML}</div>`
}
 function renderSlate(){for(const g of slate){const p=model(g);if(p)syncPick(g,p)}const q=$('nflSearch').value.trim().toLowerCase(),conf=$('nflConf').value,state=$('nflState').value,arr=slate.filter(g=>(!q||`${g.away.name} ${g.home.name} ${g.away.abbr} ${g.home.abbr}`.toLowerCase().includes(q))&&(!conf||g.away.conf===conf||g.home.conf===conf)&&(!state||g.state===state));const by=new Map();for(const g of arr){const d=date(g.date);if(!by.has(d))by.set(d,[]);by.get(d).push(g)}$('nflDays').innerHTML=[...by].map(([d,gs])=>`<div class="college-day"><div class="college-day-head"><b>${esc(d)}</b><span>${gs.length} GAME${gs.length===1?'':'S'}</span></div><div class="college-games">${gs.map(gameCard).join('')}</div></div>`).join('');$('nflEmpty').hidden=!!arr.length;$('nflGameCount').textContent=arr.length;$('nflProjectedCount').textContent=arr.filter(model).length;$('nflTeamCount').textContent=new Set(arr.flatMap(g=>[g.away.abbr,g.home.abbr])).size;}
 async function fetchJSON(url){const r=await fetch(url,{cache:'no-store',signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error('Feed returned '+r.status);return r.json()}
 async function loadWeek(){const token=++loadToken;closeGame();slate=[];$('nflDays').innerHTML=empty('Loading NFL schedule…');$('nflEmpty').hidden=true;$('nflSyncText').textContent='SYNCING';$('nflPrevWeek').disabled=week===1;$('nflNextWeek').disabled=week===18;
  try {const j=await fetchJSON(`${api}scoreboard?dates=${season}&seasontype=2&week=${week}&limit=100`);if(token!==loadToken)return;slate=(j.events||[]).map(parse).filter(Boolean).sort((a,b)=>new Date(a.date)-new Date(b.date));renderSlate();$('nflSyncText').textContent='LIVE SCHEDULE';$('nflSyncDot').style.background='#19d879';$('nflUpdated').textContent=new Date().toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});}
  catch(e){if(token!==loadToken)return;$('nflSyncText').textContent='SCHEDULE UNAVAILABLE';$('nflSyncDot').style.background='#ff5364';$('nflDays').innerHTML=empty('NFL schedule could not be loaded. Use Refresh to try again.');['nflGameCount','nflProjectedCount','nflTeamCount','nflUpdated'].forEach(id=>$(id).textContent='—');}
 }
 function colors(g){const valid=(v,f)=>/^[0-9a-f]{6}$/i.test(v||'')?'#'+v:f;let a=valid(g.away.color,'#168cff'),h=valid(g.home.color,'#55e59b');const rgb=c=>c.slice(1).match(/../g).map(x=>parseInt(x,16)),distance=(x,y)=>Math.hypot(...rgb(x).map((v,i)=>v-rgb(y)[i]));const bright=c=>rgb(c).reduce((s,v)=>s+v,0);if(bright(a)<120)a=valid(g.away.altColor,'#7bc6ff');if(bright(h)<120)h=valid(g.home.altColor,'#55e59b');if(distance(a,h)<80)h=valid(g.home.altColor,'#55e59b');if(distance(a,h)<80)h='#d6e8f7';root.style.setProperty('--cgAway',a);root.style.setProperty('--cgHome',h);return {a,h};}
 function winBar(g,p){return `<div style="display:flex;justify-content:space-between;font-size:11px;font-weight:1000"><span class="nfl-away">${g.away.abbr} ${pct(p.ap)}</span><span class="nfl-home">${g.home.abbr} ${pct(p.hp)}</span></div><div class="cg-team-bar"><i class="away" style="width:${p.ap*100}%"></i><i class="home" style="width:${p.hp*100}%"></i></div>`}
 function kpis(items){return items.map(([label,value,accent=''])=>`<div class="cg-kpi ${accent}"><span>${esc(label)}</span><b>${esc(value)}</b></div>`).join('')}
 function table(g,rows){return `<table class="nfl-table"><thead><tr><th>METRIC</th><th class="nfl-away">${g.away.abbr}</th><th class="nfl-home">${g.home.abbr}</th></tr></thead><tbody>${rows.map(([label,a,h])=>`<tr><td>${esc(label)}</td><td>${esc(a)}</td><td>${esc(h)}</td></tr>`).join('')}</tbody></table>`}
 function renderProjection(g,p){if(!p){['nflGameCenter','nflWinProb','nflProjectionKpis','nflModelInputs','nflCalibration','nflPredictions','nflAnalytics','nflBox'].forEach(id=>$(id).innerHTML=empty('NFL model profiles are unavailable for this matchup.'));return;}
  $('nflGameCenter').innerHTML=AdvantageModel.card(p.forecast,true,AWM_DATA.NFL)+row('Matchup',`${g.away.name} at ${g.home.name}`)+row('GRIDLOCK projected score',`${fixed(p.away.points)} – ${fixed(p.home.points)}`)+row('Projected margin',`${p.margin>=0?g.home.abbr:g.away.abbr} ${fixed(Math.abs(p.margin))}`)+row('Projected total',fixed(p.total))+row('Model','AWM V3 NFL')+row('Market comparison',market(g))+row('Venue',g.venue||'—')+(window.GridlockPicks?window.GridlockPicks.detailHTML('NFL',g.id):'');
  $('nflWinProb').innerHTML=winBar(g,p)+row('Most likely winner',p.hp>=.5?g.home.name:g.away.name)+row('Win probability',pct(Math.max(p.ap,p.hp)));
  $('nflProjectionKpis').innerHTML=kpis([['AWAY',fixed(p.away.points),'away-accent'],['HOME',fixed(p.home.points),'home-accent'],['TOTAL',fixed(p.total)],['MARGIN',fixed(p.margin),p.margin>=0?'home-accent':'away-accent']]);
  $('nflModelInputs').innerHTML=row('Football matchup • 60%',fixed(p.edge.football))+row('Power • 35%',fixed(p.edge.power))+row('Current form • 5%',fixed(p.edge.form))+row('Internal model margin',fixed(p.edge.margin))+row('Source','Verified histories through '+AWM_DATA.NFL.asOf);
  $('nflCalibration').innerHTML=row('Model source','Advantage Winner Model V3 • NFL')+row('Market spread',g.market.details||'Unavailable')+row('Market total',g.market.total??'Unavailable')+row('Market home margin',g.market.margin??'Unavailable')+row('Market treatment','Comparison only; does not change projection');
  const pred=(title,sub)=>`<div class="cg-pred good"><div class="cg-pred-title">${esc(title)}</div><div class="cg-pred-sub">${esc(sub)}</div></div>`;
  let predictions=pred(`${p.hp>=.5?g.home.name:g.away.name} TO WIN • ${pct(Math.max(p.hp,p.ap))}`,`GRIDLOCK projects ${g.away.abbr} ${fixed(p.away.points)} – ${g.home.abbr} ${fixed(p.home.points)}.`);
  if(g.market.margin!==null){const edge=p.margin-g.market.margin;predictions+=pred(`SPREAD LEAN: ${edge>=0?g.home.name:g.away.name} • ${fixed(Math.abs(edge))}-PT MODEL EDGE${window.GridlockPicks&&window.GridlockPicks.tier('NFL',Math.abs(edge))?' • '+window.GridlockPicks.stars(window.GridlockPicks.tier('NFL',Math.abs(edge)))+' '+window.GridlockPicks.tier('NFL',Math.abs(edge))+'-STAR':''}`,`Model home margin ${fixed(p.margin)} vs market home margin ${fixed(g.market.margin)}.`)}
  if(g.market.total!==null){const edge=p.total-g.market.total;predictions+=pred(`TOTAL LEAN: ${edge>=0?'OVER':'UNDER'} ${g.market.total} • ${fixed(Math.abs(edge))}-PT EDGE`,`Model total ${fixed(p.total)}. Market lines are comparison-only.`)}
  $('nflPredictions').innerHTML=predictions+(g.market.margin===null&&g.market.total===null?empty('Market spread and total are unavailable; no market lean is shown.'):'');
  const a=AdvantageModel.team(AWM_DATA.NFL,g.away),h=AdvantageModel.team(AWM_DATA.NFL,g.home);
  $('nflAnalytics').innerHTML=table(g,[['Offensive yards/play',fixed(a.off.ypp),fixed(h.off.ypp)],['Defensive yards/play',fixed(a.defense.ypp),fixed(h.defense.ypp)],['Median gain',fixed(a.off.median),fixed(h.off.median)],['Explosive rate',pct(a.off.expl),pct(h.off.expl)],['Negative-play rate',pct(a.off.neg),pct(h.off.neg)],['Power',fixed(a.elo),fixed(h.elo)],['Current form',fixed(a.form),fixed(h.form)]]);
  $('nflBox').innerHTML=table(g,[['Points','points'],['Yards','totalYds'],['Pass yards','passYds'],['Rush yards','rushYds'],['Plays','plays'],['Pass attempts','att'],['Completions','comp'],['Rush attempts','rushAtt'],['First downs','firstDowns']].map(([label,k])=>[label,fixed(p.away[k]),fixed(p.home[k])]));
 }
 function setTab(value){tab=value;root.querySelectorAll('[data-nfl-tab]').forEach(el=>{el.classList.toggle('active',el.dataset.nflTab===value);el.setAttribute('aria-selected',el.dataset.nflTab===value)});root.querySelectorAll('[data-nfl-panel]').forEach(el=>el.classList.toggle('active',el.dataset.nflPanel===value));if(value==='simulator')simulate();if(value==='chat')renderChat();}
 function syncLegacy(g){const idx=games.findIndex(x=>x[0]===g.away.abbr&&x[1]===g.home.abbr);if(idx>=0)activeGame=idx;else{games.push([g.away.abbr,g.home.abbr]);activeGame=games.length-1}render();}
 function openGame(g){syncLegacy(g);selected=g;projection=model(g);if(projection)syncPick(g,projection);lastSummary=null;colors(g);$('nflSlate').hidden=true;document.body.classList.add('nfl-game-open');detail.classList.add('open');for(const side of ['Away','Home']){const t=g[side.toLowerCase()];$('nfl'+side+'Name').textContent=t.name;$('nfl'+side+'Meta').textContent=`${t.conf} • ${t.record||season} • ${side.toUpperCase()}`;$('nfl'+side+'Logo').src=t.logo;$('nfl'+side+'Logo').alt=t.name+' logo';$('nfl'+side+'Score').textContent=projection?fixed(projection[side.toLowerCase()].points):'—';}
  $('nflDate').textContent=date(g.date)+' • '+time(g.date);$('nflNetwork').textContent=[g.network,g.venue].filter(Boolean).join(' • ');$('nflMarket').textContent=market(g);$('nflStatus').textContent=g.status.toUpperCase();renderProjection(g,projection);setTab('gamecast');resetLive(g);refreshLive();window.scrollTo({top:0,behavior:'smooth'});
 }
 function closeGame(){++liveToken;selected=null;projection=null;lastSummary=null;document.body.classList.remove('nfl-game-open');detail.classList.remove('open');$('nflSlate').hidden=false;}
 function resetLive(g){PlayRibbons.update($('nflPlayRibbon'),g.id,[],false);$('nflTopLiveStamp').textContent=g.complete?'FINAL':g.state==='in'?'LIVE':'PREGAME';$('nflLiveProjectionStamp').textContent='WAITING';$('nflLiveHero').innerHTML=empty('Live score activates after kickoff.');['nflTopLiveProb','nflFieldState','nflMomentum','nflLiveProjection','nflLiveMarket','nflPlayByPlay'].forEach(id=>$(id).innerHTML=empty(g.state==='pre'?'Live data activates after kickoff.':'Loading NFL live feed…'));}
 async function refreshLive(){if(!selected||document.body.classList.contains('college-mode'))return;const g=selected,token=++liveToken;try{const j=await fetchJSON(api+'summary?event='+encodeURIComponent(g.id));if(token!==liveToken||selected!==g)return;lastSummary=j;renderLive(g,j)}catch(e){if(token!==liveToken)return;$('nflFootballFeedStatus').textContent='FEED UNAVAILABLE';$('nflPlayByPlay').innerHTML=empty('Live feed unavailable. Retrying automatically; pregame projections are unchanged.');}}
 function renderLive(g,j){const c=j.header?.competitions?.[0]||{},st=c.status||{},state=st.type?.state||g.state,done=!!st.type?.completed,cs=c.competitors||[],a=cs.find(x=>x.homeAway==='away'),h=cs.find(x=>x.homeAway==='home');const as=num(a?.score),hs=num(h?.score),label=st.type?.shortDetail||g.status;
  $('nflFootballFeedStatus').textContent='ESPN NFL • '+new Date().toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});$('nflTopLiveStamp').textContent=done?'FINAL':state==='in'?'LIVE':'PREGAME';$('nflStatus').textContent=label.toUpperCase();
  if(done&&projection&&window.GridlockPicks){g.complete=true;g.away.score=as;g.home.score=hs;syncPick(g,projection);renderProjection(g,projection)}
  if(state==='pre'){resetLive(g);$('nflFootballFeedStatus').textContent='ESPN NFL • PREGAME';return;}
  if(!$('nflPlayRibbon'))$('nflLiveHero').insertAdjacentHTML('afterend','<div id="nflPlayRibbon" class="play-ribbon-host"></div>');
  $('nflLiveHero').innerHTML=`<div class="nfl-live-score"><div class="nfl-away">${esc(g.away.name)}<div class="nfl-score-actual">${as??'—'}</div></div><div>${esc(label)}</div><div class="nfl-home">${esc(g.home.name)}<div class="nfl-score-actual">${hs??'—'}</div></div></div>`;
  const verified=AdvantageModel.espnState(j,g),live=verified&&AdvantageModel.live(AWM_DATA.NFL,projection?.forecast,verified);$('nflTopLiveProb').innerHTML=live?winBar(g,{hp:live.homeWin,ap:1-live.homeWin})+row('Live model',live.mode||'Final result'):empty('Verified prior, score and regulation clock required.');
  const sit=c.situation||j.situation||{},pos=cs.find(x=>String(x.id||x.team?.id)===String(sit.possession));$('nflFieldState').innerHTML=row('Possession',pos?.team?.displayName||'Unavailable')+row('Down & distance',sit.downDistanceText||'Unavailable')+row('Field position',sit.possessionText||'Unavailable')+row('Clock',st.displayClock||'—')+row('Period',st.period||'—');
  const bt=j.boxscore?.teams||[],ba=bt.find(x=>String(x.team?.id)===String(g.away.id)),bh=bt.find(x=>String(x.team?.id)===String(g.home.id));const stat=(t,k)=>t?.statistics?.find(x=>x.name===k)?.displayValue||'—';$('nflMomentum').innerHTML=table(g,[['Total yards','totalYards'],['First downs','firstDowns'],['Turnovers','turnovers'],['Possession','possessionTime']].map(([label,k])=>[label,stat(ba,k),stat(bh,k)]));
  // AWM remains the frozen pregame prediction. Do not invent a live NFL projection.
  $('nflLiveProjectionStamp').textContent=done?'FINAL':'LIVE';$('nflLiveProjection').innerHTML=row(done?'Final score':'Current score',`${g.away.abbr} ${as??'—'} – ${g.home.abbr} ${hs??'—'}`)+(projection?row('Pregame AWM projection',`${fixed(projection.away.points)} – ${fixed(projection.home.points)}`):'')+(live?row('Live AWM projected score',fixed(live.away)+' – '+fixed(live.home)):empty('Live projection unavailable for this game state.'));
  const plays=[...(j.drives?.previous||[]),...(j.drives?.current?[j.drives.current]:[])].flatMap(d=>d.plays||[]);if(!plays.length)plays.push(...(j.plays||[]));const unique=[...new Map(plays.map((p,i)=>[p.id||i,p])).values()];PlayRibbons.update($('nflPlayRibbon'),g.id,unique.slice().reverse(),state==='in'&&!done);$('nflPlayByPlay').innerHTML=unique.length?unique.slice(-50).reverse().map(p=>`<div class="nfl-pbp"><b>${esc(p.period?.displayValue||'')} ${esc(p.clock?.displayValue||'')}</b><div>${esc(p.text||p.shortText||'')}</div></div>`).join(''):empty('No play-by-play available yet.');
 }
 function histogram(id,values,marker,color){const canvas=$(id),ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);const lo=Math.floor(values.reduce((a,b)=>Math.min(a,b),Infinity)/5)*5,hi=Math.ceil(values.reduce((a,b)=>Math.max(a,b),-Infinity)/5)*5||5,bins=Array(24).fill(0),range=Math.max(1,hi-lo);values.forEach(v=>bins[Math.min(23,Math.floor((v-lo)/range*24))]++);const max=Math.max(...bins);bins.forEach((v,i)=>{ctx.fillStyle=color;ctx.fillRect(35+i*(w-50)/24,h-30-v/max*(h-55),(w-50)/24-2,v/max*(h-55))});ctx.fillStyle='#9ab0c0';ctx.font='12px sans-serif';ctx.fillText(lo,10,h-8);ctx.fillText(hi,w-35,h-8);if(marker!==null&&marker>=lo&&marker<=hi){const x=35+(marker-lo)/range*(w-50);ctx.strokeStyle='#ffbf3f';ctx.beginPath();ctx.moveTo(x,15);ctx.lineTo(x,h-30);ctx.stroke();ctx.fillStyle='#ffbf3f';ctx.fillText('MARKET',Math.min(w-65,Math.max(0,x-20)),13)}}
 function simulate(){if(!selected||!projection){$('nflSimKpis').innerHTML=empty('Model unavailable.');return;}$('nflSimKpis').innerHTML=AdvantageModel.card(projection.forecast,true,AWM_DATA.NFL);$('nflSimDetail').textContent='Conditional targets use the fitted Advantage model. A separately validated score-distribution simulation is not available.';}
 function chatKey(){return `gridlock.nfl.chat.${season}.${selected?.id||'none'}`}
 function chatRows(){try{return JSON.parse(localStorage.getItem(chatKey())||'[]')}catch{return []}}
 function renderChat(){if(!selected)return;$('nflChatTitle').textContent=`${selected.away.name} vs ${selected.home.name} CHAT`;$('nflChatName').value=localStorage.getItem('gridlock.chat.name')||'';const rows=chatRows();$('nflChatFeed').innerHTML=rows.length?rows.map(r=>`<div class="cg-chat-msg"><div class="cg-chat-meta">${esc(r.name)} • ${esc(new Date(r.time).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}))}</div>${esc(r.msg)}</div>`).join(''):empty('No messages in this game room yet.');$('nflChatFeed').scrollTop=$('nflChatFeed').scrollHeight;}
 function sendChat(){const name=$('nflChatName').value.trim(),msg=$('nflChatInput').value.trim();if(!name){$('nflChatName').focus();return;}if(!msg)return;try{localStorage.setItem('gridlock.chat.name',name);localStorage.setItem(chatKey(),JSON.stringify([...chatRows(),{name,msg,time:Date.now()}].slice(-200)));$('nflChatInput').value='';renderChat()}catch{$('nflChatFeed').innerHTML=empty('Browser storage unavailable. Message could not be saved.')}}
 $('nflChatInput').nextElementSibling.textContent='SEND';$('nflChatInput').closest('.cg-card-body').lastElementChild.textContent='Game-specific NFL room. Messages are saved locally in this browser.';
 $('nflPostPlay').onclick=async()=>{if(!selected||!projection)return;const text=`NFL • ${selected.away.name} at ${selected.home.name}\nAWM V3 projection: ${fixed(projection.away.points)} – ${fixed(projection.home.points)}\nWin probability: ${selected.away.abbr} ${pct(projection.ap)} • ${selected.home.abbr} ${pct(projection.hp)}\n${market(selected)} (comparison only)`;try{await navigator.clipboard.writeText(text);$('nflPostPlay').textContent='COPIED'}catch{$('nflPostPlay').textContent='COPY UNAVAILABLE'}setTimeout(()=>{$('nflPostPlay').textContent='COPY PROJECTION'},2500)};
 $('nflBack').onclick=()=>{closeGame();window.scrollTo({top:0,behavior:'smooth'})};$('nflTabs').onclick=e=>{const b=e.target.closest('[data-nfl-tab]');if(b)setTab(b.dataset.nflTab)};
 $('nflDays').onclick=e=>{
 const b=e.target.closest('[data-nfl-game]');if(!b)return;
 const g=slate.find(g=>g.id===b.dataset.nflGame);if(!g)return;
 const p=model(g);
 if(window.handleMainCardShareClick&&window.handleMainCardShareClick(e,b,g,'NFL',p))return;
 openGame(g)
};
 $('nflWeek').value=week;$('nflWeek').onchange=()=>{week=+$('nflWeek').value;loadWeek()};$('nflPrevWeek').onclick=()=>{week=Math.max(1,week-1);$('nflWeek').value=week;loadWeek()};$('nflNextWeek').onclick=()=>{week=Math.min(18,week+1);$('nflWeek').value=week;loadWeek()};$('nflRefresh').onclick=loadWeek;['nflConf','nflState'].forEach(id=>$(id).onchange=renderSlate);$('nflSearch').oninput=renderSlate;$('nflRunSim').onclick=simulate;$('nflChatSend').onclick=sendChat;$('nflChatInput').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();sendChat()}};
 document.querySelector('.mainnav [data-jump="matchup"]')?.addEventListener('click',closeGame);
 document.querySelector('.mainnav [data-jump="projection"]')?.addEventListener('click',()=>{if(!selected&&slate.length)openGame(slate[0]);setTab('projection')});
 // Keep the existing optional Players/News navigation accessible within the NFL shell.
 for(const [id,title] of [['players','PLAYER PROJECTIONS'],['news','NFL NEWS']])document.querySelector(`.mainnav [data-jump="${id}"]`)?.addEventListener('click',()=>{if(!selected&&slate.length)openGame(slate[0]);if(!selected)return;let panel=root.querySelector('[data-nfl-panel="'+id+'"]');if(!panel){panel=document.createElement('div');panel.className='cg-panel';panel.dataset.nflPanel=id;detail.append(panel)}panel.innerHTML=`<div class="cg-section-label">${title}</div>`+empty('Verified '+title.toLowerCase()+' are not available in this team prediction model.');setTab(id)});
 new MutationObserver(()=>{if(document.body.classList.contains('college-mode'))++liveToken;else if(selected)refreshLive()}).observe(document.body,{attributes:true,attributeFilter:['class']});
 setInterval(()=>{if(selected&&!document.hidden)refreshLive()},20000);
 // Profile files load asynchronously. Update the visible projection when they become ready.
 let attempts=0;const ready=setInterval(()=>{if(window.AWM_DATA?.NFL?.profiles){clearInterval(ready);renderSlate();if(selected){projection=model(selected);renderProjection(selected,projection);if(projection){$('nflAwayScore').textContent=fixed(projection.away.points);$('nflHomeScore').textContent=fixed(projection.home.points)}}}else if(++attempts>=60)clearInterval(ready)},250);
 window.GRIDLOCK_NFL_CENTER={getGames:()=>slate,getProjection:model,openGame:id=>{const g=slate.find(g=>g.id===String(id));if(g)openGame(g)}};
 loadWeek();
})();
