
(()=>{
const P=window.POWER4_DATA;if(!P)return;
const $=id=>document.getElementById(id);let metric='density',cellCache=new Map();
const esc=s=>String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]));
function addOpts(id,arr,labelFn=x=>x){const el=$(id);arr.forEach(x=>{const o=document.createElement('option');o.value=x;o.textContent=labelFn(x);el.appendChild(o)})}
addOpts('p4Cov',P.coverages);addOpts('p4Route',P.routes);
const playerSel=$('p4Player');
function clearSelect(id,placeholder){const el=$(id);el.innerHTML='';const o=document.createElement('option');o.value='';o.textContent=placeholder;el.appendChild(o);return el}
function addTeamOption(el,code,label,disabled=false){const o=document.createElement('option');o.value=code||'';o.textContent=label;o.disabled=disabled;el.appendChild(o)}
function playerEligible(p){return (p.tgt||0)>=1 || (p.att||0)>=20}
function fillPlayers(codes=null){clearSelect('p4Player','SELECT PLAYER');P.players.filter(playerEligible).filter(p=>!codes||codes.includes(p.code)).forEach(p=>{const o=document.createElement('option');o.value=p.key;o.dataset.code=p.code;o.textContent=`${p.name} — ${p.team}${p.num>=0?' #'+p.num:''} ${p.pos}`;playerSel.appendChild(o)})}
function fillAllTeams(){const off=clearSelect('p4Off','ALL TEAMS'),def=clearSelect('p4Def','ALL DEFENSES');P.teams.forEach(code=>addTeamOption(off,code,P.teamMap[code]?.team?`${P.teamMap[code].team} (${code})`:code));P.defenses.forEach(code=>addTeamOption(def,code,P.teamMap[code]?.team?`${P.teamMap[code].team} (${code})`:code));fillPlayers(null)}
fillAllTeams();
function modelCode(name){try{return window.GRIDLOCK_COLLEGE_MODEL?.rating(name)?.code||null}catch(e){return null}}
window.GRIDLOCK_SCOPE_P4_GAME=function(game){if(!game){fillAllTeams();$('p4View').value='team';$('p4Off').value='';$('p4Def').value='';$('p4Player').value='';run();return}const awayCode=modelCode(game.away?.school||game.away?.name),homeCode=modelCode(game.home?.school||game.home?.name),codes=[awayCode,homeCode].filter(Boolean),off=clearSelect('p4Off','SELECT GAME TEAM'),def=clearSelect('p4Def','SELECT OPPONENT DEFENSE');[[game.away?.name,awayCode],[game.home?.name,homeCode]].forEach(([name,code])=>{addTeamOption(off,code,code?`${name} (${code})`:`${name} — NO SPATIAL DATA`,!code);addTeamOption(def,code,code?`${name} (${code})`:`${name} — NO SPATIAL DATA`,!code)});fillPlayers(codes);$('p4View').value='team';$('p4Player').value='';$('p4Off').value=homeCode||awayCode||'';$('p4Def').value=awayCode||homeCode||'';run()};
function v(id){return $(id)?.value||''}
function commonFilter(r){return (!v('p4Cov')||r.c===v('p4Cov'))&&(!v('p4Shell')||r.s===v('p4Shell'))&&(!v('p4Grp')||r.g===v('p4Grp'))&&(!v('p4Down')||String(r.dn)===v('p4Down'))&&(!v('p4Route')||r.r===v('p4Route'))}
function selectedRows(){let rows=P.points.filter(commonFilter);if(v('p4View')==='player'&&v('p4Player'))rows=rows.filter(r=>r.pk===v('p4Player'));else if(v('p4Off'))rows=rows.filter(r=>r.o===v('p4Off'));return rows}
function baselineRows(){return P.points.filter(commonFilter)}
function defenseRows(){let rows=P.points.filter(commonFilter);if(v('p4Def'))rows=rows.filter(r=>r.v===v('p4Def'));return rows}
function stats(rows){const n=rows.length,cp=rows.reduce((a,r)=>a+(Number(r.cp)||0),0),y=rows.reduce((a,r)=>a+(Number(r.y)||0),0),ex=rows.reduce((a,r)=>a+(Number(r.x)||0),0),eRows=rows.filter(r=>Number.isFinite(Number(r.e))),e=eRows.reduce((a,r)=>a+Number(r.e),0);return{n,cp:n?cp/n:null,ypt:n?y/n:null,ex:n?ex/n:null,epa:eRows.length?e/eRows.length:null}}
function makeGrid(rows){const xb=9,y0=-15,y1=60,st=5,yb=(y1-y0)/st,g=Array.from({length:yb},()=>Array.from({length:xb},()=>({n:0,cp:0,y:0,x:0,e:0})));for(const r of rows){let xi=Math.max(0,Math.min(xb-1,Math.floor(r.w/53.4*xb))),yi=Math.floor((r.d-y0)/st);if(yi>=0&&yi<yb){let c=g[yi][xi];c.n++;c.cp+=r.cp;c.y+=r.y;c.x+=r.x;c.e+=r.e}}return{g,xb,yb,y0,st}}
function cellValue(c,m=metric){if(!c.n)return null;if(m==='density')return c.n;if(c.n<3)return null;if(m==='comp')return c.cp/c.n;if(m==='ypt')return c.y/c.n;if(m==='expl')return c.x/c.n;return c.e/c.n}
function col(t){t=Math.max(0,Math.min(1,t));let S=[[20,55,86],[38,117,160],[241,198,85],[205,65,48]],q=t*3,i=Math.min(2,Math.floor(q)),f=q-i,a=S[i],b=S[i+1];return`rgb(${Math.round(a[0]+(b[0]-a[0])*f)},${Math.round(a[1]+(b[1]-a[1])*f)},${Math.round(a[2]+(b[2]-a[2])*f)})`}
function drawField(id,rows,mode=metric,matchData=null){const cv=$(id),ctx=cv.getContext('2d'),W=cv.width,H=cv.height;ctx.clearRect(0,0,W,H);ctx.fillStyle='#244f2b';ctx.fillRect(0,0,W,H);const G=makeGrid(rows),cw=W/G.xb,ch=H/G.yb;let vals=[];
if(matchData){for(let y=0;y<G.yb;y++)for(let x=0;x<G.xb;x++)vals.push(matchData[y][x]);}else for(const c of G.g.flat()){const z=cellValue(c,mode);if(z!==null)vals.push(z)}
let lo=0,hi=1;if(vals.length){let s=vals.filter(Number.isFinite).sort((a,b)=>a-b);if(mode==='density'||matchData){hi=s[Math.max(0,Math.floor(.95*(s.length-1)))]||Math.max(...s)||1}else{lo=s[Math.floor(.05*(s.length-1))]||0;hi=s[Math.floor(.95*(s.length-1))]||1;if(hi===lo)hi=lo+1}}
let cells=[];for(let yi=0;yi<G.yb;yi++)for(let xi=0;xi<G.xb;xi++){let c=G.g[yi][xi],z=matchData?matchData[yi][xi]:cellValue(c,mode),py=H-(yi+1)*ch;if(z!==null&&Number.isFinite(z)&&(c.n||matchData)){ctx.fillStyle=col((z-lo)/(hi-lo||1));ctx.globalAlpha=.86;ctx.fillRect(xi*cw,py,cw,ch);ctx.globalAlpha=1}cells.push({x:xi*cw,y:py,w:cw,h:ch,c,depth0:G.y0+yi*G.st,depth1:G.y0+(yi+1)*G.st,z})}
ctx.strokeStyle='rgba(255,255,255,.35)';ctx.fillStyle='rgba(255,255,255,.78)';ctx.font='11px sans-serif';for(let d=-10;d<=60;d+=10){let py=H-((d-G.y0)/G.st)*ch;ctx.beginPath();ctx.moveTo(0,py);ctx.lineTo(W,py);ctx.stroke();ctx.fillText(d===0?'LOS':`${d} yd`,6,py-4)}ctx.strokeStyle='rgba(255,255,255,.22)';[W*.39,W*.61].forEach(x=>{for(let y=0;y<H;y+=17){ctx.beginPath();ctx.moveTo(x-5,y);ctx.lineTo(x+5,y);ctx.stroke()}});cellCache.set(id,cells)}
function matchGrid(off,def){const A=makeGrid(off).g,B=makeGrid(def).g;let maxA=Math.max(...A.flat().map(c=>c.n),1),maxB=Math.max(...B.flat().map(c=>c.n),1);return A.map((row,y)=>row.map((a,x)=>{const b=B[y][x];if(!a.n||!b.n)return 0;const usage=a.n/maxA, vuln=(b.y/b.n);const epa=b.e/b.n;return usage*(b.n/maxB)*Math.max(0.25,1+Math.max(-.5,epa))*Math.max(.25,vuln/8)}))}
function profile(){const card=$('p4PlayerCard'),box=$('p4PlayerProfile');if(v('p4View')!=='player'||!v('p4Player')){card.classList.remove('show');return}const p=P.players.find(x=>x.key===v('p4Player'));if(!p)return;card.classList.add('show');let s=[];const add=(val,label)=>{if(val!==undefined)s.push(`<div class="p4-profstat"><b>${val}</b><span>${label}</span></div>`)};add(p.tgt,'TARGETS');add(p.rec,'REC');add(p.recYds,'REC YDS');add(p.recTD,'REC TD');add(p.att,'RUSH ATT');add(p.rushYds,'RUSH YDS');box.innerHTML=`<div class="p4-profile"><div class="p4-profile-main"><div class="nm">${esc(p.name)}</div><div class="meta">${esc(p.team)} • #${p.num} • ${esc(p.pos)}${p.recGrd!==undefined?` • REC GRD ${p.recGrd}`:''}${p.rushGrd!==undefined?` • RUSH GRD ${p.rushGrd}`:''}</div></div>${s.join('')}</div>`}
function intelligence(off,base,def){const os=stats(off),bs=stats(base),ds=stats(def),rows=[];function row(label,a,b,fmt=x=>x.toFixed(2),goodHigh=true){if(a==null||b==null||!Number.isFinite(a)||!Number.isFinite(b)){rows.push(`<div class="p4-intel-row"><b>${label}</b><span>N/A</span></div>`);return}let d=a-b,cls=(d===0?'':((d>0)===goodHigh?'p4-hot':'p4-cold'));rows.push(`<div class="p4-intel-row"><b>${label}</b><span class="${cls}">${fmt(a)} ${d>=0?'+':''}${fmt(d)} vs baseline</span></div>`)}
row('Yards per target',os.ypt,bs.ypt,x=>x.toFixed(2));row('EPA per target',os.epa,bs.epa,x=>x.toFixed(3));row('Explosive rate',os.ex,bs.ex,x=>(x*100).toFixed(1)+'%');if(v('p4Def')){rows.push(`<div class="p4-intel-row"><b>Opponent allowed Y/T</b><span>${ds.ypt==null?'N/A':ds.ypt.toFixed(2)}</span></div><div class="p4-intel-row"><b>Opponent allowed EPA/T</b><span>${ds.epa==null?'N/A':ds.epa.toFixed(3)}</span></div>`)}rows.push(`<div class="p4-intel-row"><b>Sample</b><span>${os.n.toLocaleString()} selected / ${bs.n.toLocaleString()} baseline</span></div>`);$('p4Intel').innerHTML=rows.join('')}
function run(){let off=selectedRows(),base=baselineRows(),def=defenseRows(),s=stats(off);$('p4N').textContent=s.n.toLocaleString();$('p4CP').textContent=s.cp==null?'N/A':(s.cp*100).toFixed(1)+'%';$('p4YPT').textContent=s.ypt==null?'N/A':s.ypt.toFixed(2);$('p4EX').textContent=s.ex==null?'N/A':(s.ex*100).toFixed(1)+'%';$('p4EPA').textContent=s.epa==null?'N/A':s.epa.toFixed(3);
$('p4OffTitle').textContent=v('p4View')==='player'&&v('p4Player')?(P.players.find(x=>x.key===v('p4Player'))?.name||'PLAYER'):(P.teamMap[v('p4Off')]?.team||v('p4Off')||'POWER 4');$('p4DefTitle').textContent=P.teamMap[v('p4Def')]?.team||v('p4Def')||'ALL DEFENSES';drawField('p4FieldOff',off);drawField('p4FieldBase',base);drawField('p4FieldDef',def);drawField('p4FieldMatch',off,'density',matchGrid(off,def));profile();intelligence(off,base,def)}
['p4View','p4Off','p4Player','p4Def','p4Cov','p4Shell','p4Grp','p4Down','p4Route'].forEach(id=>$(id).addEventListener('change',()=>{if(id==='p4Player'&&v('p4Player')){$('p4View').value='player';const p=P.players.find(x=>x.key===v('p4Player'));if(p)$('p4Off').value=p.code}if(id==='p4Off'&&v('p4Off')&&v('p4View')==='player'){const p=P.players.find(x=>x.key===v('p4Player'));if(p&&p.code!==v('p4Off'))$('p4Player').value=''}run()}));
$('p4MetricBtns').addEventListener('click',e=>{const b=e.target.closest('button[data-m]');if(!b)return;metric=b.dataset.m;document.querySelectorAll('#p4MetricBtns button').forEach(x=>x.classList.toggle('active',x===b));run()});
const tip=$('p4Tooltip');['p4FieldOff','p4FieldBase','p4FieldDef','p4FieldMatch'].forEach(id=>{const cv=$(id);cv.addEventListener('mousemove',e=>{const rc=cv.getBoundingClientRect(),x=(e.clientX-rc.left)*cv.width/rc.width,y=(e.clientY-rc.top)*cv.height/rc.height,c=(cellCache.get(id)||[]).find(q=>x>=q.x&&x<q.x+q.w&&y>=q.y&&y<q.y+q.h);if(!c||(!c.c.n&&id!=='p4FieldMatch')){tip.style.display='none';return}let a=c.c;tip.innerHTML=`<b>${c.depth0} to ${c.depth1} yd depth</b><br>Targets: ${a.n||0}${a.n?`<br>Comp: ${(100*a.cp/a.n).toFixed(1)}%<br>Y/T: ${(a.y/a.n).toFixed(2)}<br>Explosive: ${(100*a.x/a.n).toFixed(1)}%<br>EPA/T: ${(a.e/a.n).toFixed(3)}`:''}`;tip.style.left=(e.clientX+12)+'px';tip.style.top=(e.clientY+12)+'px';tip.style.display='block'});cv.addEventListener('mouseleave',()=>tip.style.display='none')});
run();
})();
