const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),cp=require('child_process');
const {JSDOM}=require('jsdom');
const repo=__dirname+'/../';
function engine(source){const ctx={window:{},document:{createElement:()=>({}),head:{appendChild(){}}},console};vm.createContext(ctx);for(const f of ['awm_college_profiles.js','awm_college_exact.js','awm_college_aliases.js','awm_nfl_profiles.js'])vm.runInContext(fs.readFileSync(repo+f,'utf8'),ctx);source=source.replace('function activate(){','window.testNFL={matchup:nmatch,project:nproject,profile:np};function activate(){');vm.runInContext(source,ctx);return ctx.window;}
const original=engine(cp.execFileSync('git',['show','9381498:college_model.js'],{cwd:repo,encoding:'utf8'}));const updated=engine(fs.readFileSync(repo+'college_model.js','utf8'));let checked=0;for(const a of Object.keys(original.AWM_NFL_PROFILES))for(const h of Object.keys(original.AWM_NFL_PROFILES)){if(a===h)continue;const p=original.testNFL.matchup(a,h);assert.equal(JSON.stringify(p),JSON.stringify(updated.testNFL.matchup(a,h)));assert.equal(JSON.stringify(original.testNFL.project(a,h,p.p)),JSON.stringify(updated.testNFL.project(a,h,p.p)));checked++;}for(const key of Object.keys(original.AWM_COLLEGE_EXACT_W4)){const [a,h]=key.split('@@');assert.equal(JSON.stringify(original.GRIDLOCK_COLLEGE_MODEL.project(a,h,false,{})),JSON.stringify(updated.GRIDLOCK_COLLEGE_MODEL.project(a,h,false,{})));}console.log('Unchanged model outputs:',checked,'NFL matchups and',Object.keys(original.AWM_COLLEGE_EXACT_W4).length,'NCAA workbook games');
const html=fs.readFileSync(repo+'index.html','utf8');const dom=new JSDOM(html,{url:'http://localhost/',runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window;w.Date.now=()=>Date.UTC(2026,8,23);w.scrollTo=()=>{};w.HTMLCanvasElement.prototype.getContext=()=>new Proxy({},{get:(t,k)=>t[k]||(()=>{}),set:(t,k,v)=>(t[k]=v,true)});
w.eval('var games=[];var activeGame=0;function render(){};function scoreDraw(a,h){return [Math.round(a),Math.round(h)]}');Object.assign(w,updated);let fetches=[],fail=false,summary={},responses={};const fixture=JSON.parse(fs.readFileSync(__dirname+'/fixtures/nfl-week3.json','utf8'));w.fetch=async url=>{fetches.push(url);if(fail)throw Error('offline');return{ok:true,json:async()=>url.includes('summary')?summary:responses[url]||fixture}};
w.eval(fs.readFileSync(repo+'nfl-center.js','utf8'));const tick=()=>new Promise(r=>setTimeout(r,20)), $=id=>w.document.getElementById(id);
(async()=>{await tick();assert.equal(w.GRIDLOCK_NFL_CENTER.getGames().length,16);assert.equal(w.document.querySelectorAll('[data-nfl-game]').length,16);const ids=[...w.document.querySelectorAll('[id]')].map(e=>e.id);assert.equal(ids.length,new Set(ids).size,'Unique IDs across both leagues');const sourceTabs=[...w.document.querySelectorAll('#cgTabs [data-cg]')].map(e=>e.dataset.cg);assert.deepEqual([...w.document.querySelectorAll('[data-nfl-tab]')].map(e=>e.dataset.nflTab),sourceTabs);
$('nflSearch').value='Buffalo';$('nflSearch').dispatchEvent(new w.Event('input'));assert.equal(w.document.querySelectorAll('[data-nfl-game]').length,1);$('nflSearch').value='';$('nflSearch').dispatchEvent(new w.Event('input'));
const g=w.GRIDLOCK_NFL_CENTER.getGames()[0];const before=w.GRIDLOCK_NFL_CENTER.getProjection(g);w.GRIDLOCK_NFL_CENTER.openGame(g.id);await tick();assert($('nflGamecast').classList.contains('open'));assert($('nflSlate').hidden);assert($('nflGameCenter').textContent.includes(g.away.name));for(const tab of sourceTabs){w.document.querySelector(`[data-nfl-tab="${tab}"]`).click();assert(w.document.querySelector(`[data-nfl-panel="${tab}"]`).classList.contains('active'));assert.equal(w.document.querySelectorAll('#nflGamecast .cg-panel.active').length,1);}
g.market.margin=null;g.market.total=null;g.market.details='';w.GRIDLOCK_NFL_CENTER.openGame(g.id);await tick();assert(!$('nflPredictions').textContent.includes('SPREAD LEAN'));assert(!$('nflPredictions').textContent.includes('TOTAL LEAN'));assert.equal(JSON.stringify(before),JSON.stringify(w.GRIDLOCK_NFL_CENTER.getProjection(g)),'Market independent');w.document.querySelector('[data-nfl-tab="simulator"]').click();assert(!$('nflSimDetail').textContent.includes('covers market'));assert(!$('nflSimDetail').textContent.includes('Over 0'));
summary={header:{competitions:[{status:{type:{state:'in',shortDetail:'7:30 - 2nd'},displayClock:'7:30',period:2},competitors:[{homeAway:'away',score:'0',team:{id:g.away.id}},{homeAway:'home',score:'7',team:{id:g.home.id}}],situation:{downDistanceText:'2nd & 5',possessionText:'GB 25'}}]},winprobability:[{homeWinPercentage:.75}],drives:{current:{plays:[{id:'p1',text:'Pass complete for 10 yards',clock:{displayValue:'7:30'},period:{displayValue:'2nd'}}]}}};w.GRIDLOCK_NFL_CENTER.openGame(g.id);await tick();assert($('nflLiveHero').textContent.includes('7:30 - 2nd'));assert($('nflTopLiveProb').textContent.includes('75.0%'));assert($('nflPlayByPlay').textContent.includes('Pass complete'));assert($('nflFieldState').textContent.includes('2nd & 5'));
summary.header.competitions[0].status.type={state:'post',completed:true,shortDetail:'Final'};w.GRIDLOCK_NFL_CENTER.openGame(g.id);await tick();assert.equal($('nflTopLiveStamp').textContent,'FINAL');assert($('nflTopLiveProb').textContent.includes('wins'));
$('nflChatName').value='Local test';$('nflChatInput').value='<script>test</script>';$('nflChatSend').click();assert($('nflChatFeed').textContent.includes('<script>test</script>'));assert.equal($('nflChatFeed').querySelectorAll('script').length,0);w.GRIDLOCK_NFL_CENTER.openGame(w.GRIDLOCK_NFL_CENTER.getGames()[1].id);w.document.querySelector('[data-nfl-tab="chat"]').click();assert(!$('nflChatFeed').textContent.includes('Local test'));
$('nflBack').click();assert(!$('nflSlate').hidden);$('nflNextWeek').click();await tick();assert(fetches.at(-1).includes('week=4'));fail=true;$('nflRefresh').click();await tick();assert.equal($('nflSyncText').textContent,'SCHEDULE UNAVAILABLE');assert.equal($('nflGameCount').textContent,'—');assert(fetches.every(url=>url.includes('/nfl/')));console.log('PASS: slate, filters, week navigation, six tabs, model adapter, absent market, live/final state, chat isolation/escaping, feed errors, unique IDs and NFL-only endpoints');w.close();})();
